"""Stage 21 autonomous enterprise intelligence and compliance records."""
import uuid
from datetime import datetime, timezone
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base
def uid(): return str(uuid.uuid4())
def now(): return datetime.now(timezone.utc)

class ConnectorCredentialLease(Base):
 __tablename__="connector_credential_leases";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);installation_id:Mapped[str]=mapped_column(ForeignKey("connector_installations.id",ondelete="CASCADE"),index=True);provider:Mapped[str]=mapped_column(String(30));secret_reference:Mapped[str]=mapped_column(String(500));secret_fingerprint:Mapped[str]=mapped_column(String(64));region:Mapped[str]=mapped_column(String(24),default="global");egress_policy:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="active");rotated_from_id:Mapped[str|None]=mapped_column(ForeignKey("connector_credential_leases.id",ondelete="SET NULL"));expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));last_health_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ApprovalRun(Base):
 __tablename__="approval_runs";__table_args__=(UniqueConstraint("organization_id","idempotency_key",name="uq_approval_run_idempotency"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);flow_id:Mapped[str]=mapped_column(ForeignKey("approval_flows.id",ondelete="RESTRICT"));subject_type:Mapped[str]=mapped_column(String(50));subject_id:Mapped[str]=mapped_column(String(64));idempotency_key:Mapped[str]=mapped_column(String(160));status:Mapped[str]=mapped_column(String(20),default="running");context:Mapped[dict]=mapped_column(JSON,default=dict);signature_chain:Mapped[list]=mapped_column(JSON,default=list);compensation_log:Mapped[list]=mapped_column(JSON,default=list);started_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class ApprovalNodeRun(Base):
 __tablename__="approval_node_runs";__table_args__=(UniqueConstraint("run_id","node_id",name="uq_approval_node_run"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);run_id:Mapped[str]=mapped_column(ForeignKey("approval_runs.id",ondelete="CASCADE"),index=True);node_id:Mapped[str]=mapped_column(String(80));node_type:Mapped[str]=mapped_column(String(30));status:Mapped[str]=mapped_column(String(20),default="pending");assignee_id:Mapped[str|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));delegated_to_id:Mapped[str|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));decision:Mapped[str]=mapped_column(String(20),default="");signature:Mapped[str]=mapped_column(String(64),default="");due_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class CausalExperiment(Base):
 __tablename__="causal_experiments";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));metric_key:Mapped[str]=mapped_column(String(100));method:Mapped[str]=mapped_column(String(30),default="difference_in_differences");treatment:Mapped[dict]=mapped_column(JSON,default=dict);control:Mapped[dict]=mapped_column(JSON,default=dict);confounders:Mapped[list]=mapped_column(JSON,default=list);window:Mapped[dict]=mapped_column(JSON,default=dict);minimum_sample:Mapped[int]=mapped_column(Integer);power:Mapped[float]=mapped_column(Float,default=0);effect:Mapped[float|None]=mapped_column(Float);confidence_interval:Mapped[list]=mapped_column(JSON,default=list);status:Mapped[str]=mapped_column(String(20),default="draft");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class FinancialLedger(Base):
 __tablename__="financial_ledger";__table_args__=(UniqueConstraint("organization_id","external_reference",name="uq_financial_external_ref"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);entry_type:Mapped[str]=mapped_column(String(30));department:Mapped[str]=mapped_column(String(100),default="unallocated");amount_cents:Mapped[int]=mapped_column(Integer);currency:Mapped[str]=mapped_column(String(3),default="CNY");external_reference:Mapped[str]=mapped_column(String(160));provider:Mapped[str]=mapped_column(String(30),default="internal");status:Mapped[str]=mapped_column(String(20),default="posted");metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class BillingDocument(Base):
 __tablename__="billing_documents";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);document_type:Mapped[str]=mapped_column(String(20));period:Mapped[str]=mapped_column(String(7));amount_cents:Mapped[int]=mapped_column(Integer);tax_cents:Mapped[int]=mapped_column(Integer,default=0);currency:Mapped[str]=mapped_column(String(3),default="CNY");status:Mapped[str]=mapped_column(String(20),default="draft");provider_reference:Mapped[str]=mapped_column(String(160),default="");checksum:Mapped[str]=mapped_column(String(64));issued_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PrivacyBudget(Base):
 __tablename__="privacy_budgets";__table_args__=(UniqueConstraint("organization_id","dataset_key","period",name="uq_privacy_budget"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);dataset_key:Mapped[str]=mapped_column(String(100));period:Mapped[str]=mapped_column(String(7));epsilon_limit:Mapped[float]=mapped_column(Float);epsilon_used:Mapped[float]=mapped_column(Float,default=0);delta:Mapped[float]=mapped_column(Float,default=0.00001);minimum_cohort:Mapped[int]=mapped_column(Integer,default=10);status:Mapped[str]=mapped_column(String(20),default="active")
class PrivacyQueryAudit(Base):
 __tablename__="privacy_query_audits";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);budget_id:Mapped[str]=mapped_column(ForeignKey("privacy_budgets.id",ondelete="CASCADE"));query_fingerprint:Mapped[str]=mapped_column(String(64));epsilon_cost:Mapped[float]=mapped_column(Float);cohort_size:Mapped[int]=mapped_column(Integer);attack_risk:Mapped[float]=mapped_column(Float,default=0);status:Mapped[str]=mapped_column(String(20));created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PolicyBundle(Base):
 __tablename__="policy_bundles";__table_args__=(UniqueConstraint("organization_id","key",name="uq_policy_bundle_key"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);key:Mapped[str]=mapped_column(String(80));name:Mapped[str]=mapped_column(String(160));current_version:Mapped[int]=mapped_column(Integer,default=0);active_version:Mapped[int|None]=mapped_column(Integer);canary_percent:Mapped[int]=mapped_column(Integer,default=0);created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class PolicyVersion(Base):
 __tablename__="policy_versions";__table_args__=(UniqueConstraint("bundle_id","version",name="uq_policy_version"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);bundle_id:Mapped[str]=mapped_column(ForeignKey("policy_bundles.id",ondelete="CASCADE"));version:Mapped[int]=mapped_column(Integer);rules:Mapped[dict]=mapped_column(JSON,default=dict);test_cases:Mapped[list]=mapped_column(JSON,default=list);simulation:Mapped[dict]=mapped_column(JSON,default=dict);checksum:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="draft");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class RecoveryDrill(Base):
 __tablename__="recovery_drills";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);region:Mapped[str]=mapped_column(String(24));drill_type:Mapped[str]=mapped_column(String(40));rpo_target_minutes:Mapped[int]=mapped_column(Integer);rto_target_minutes:Mapped[int]=mapped_column(Integer);actual_rpo_minutes:Mapped[int|None]=mapped_column(Integer);actual_rto_minutes:Mapped[int|None]=mapped_column(Integer);evidence:Mapped[dict]=mapped_column(JSON,default=dict);isolation_verified:Mapped[bool]=mapped_column(Boolean,default=False);status:Mapped[str]=mapped_column(String(20),default="planned");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ComplianceControl(Base):
 __tablename__="compliance_controls";__table_args__=(UniqueConstraint("organization_id","framework","control_key",name="uq_compliance_control"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);framework:Mapped[str]=mapped_column(String(30));control_key:Mapped[str]=mapped_column(String(60));title:Mapped[str]=mapped_column(String(200));owner_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));status:Mapped[str]=mapped_column(String(20),default="open");exceptions:Mapped[list]=mapped_column(JSON,default=list);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class ComplianceEvidence(Base):
 __tablename__="compliance_evidence";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);control_id:Mapped[str]=mapped_column(ForeignKey("compliance_controls.id",ondelete="CASCADE"));evidence_type:Mapped[str]=mapped_column(String(40));locator:Mapped[str]=mapped_column(String(500));checksum:Mapped[str]=mapped_column(String(64));collected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class SafetyEvaluation(Base):
 __tablename__="safety_evaluations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);target_type:Mapped[str]=mapped_column(String(40));target_id:Mapped[str]=mapped_column(String(64));scenario:Mapped[str]=mapped_column(String(100));results:Mapped[dict]=mapped_column(JSON,default=dict);permission_drift:Mapped[bool]=mapped_column(Boolean,default=False);rollback_verified:Mapped[bool]=mapped_column(Boolean,default=False);score:Mapped[float]=mapped_column(Float,default=0);gate_status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
