"""Stage 27 global cognitive infrastructure and long-horizon governance."""
import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,Float,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
def uid()->str:return str(uuid.uuid4())
def now()->datetime:return datetime.now(timezone.utc)
class ProofCertification(Base):
 __tablename__="proof_certifications";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);standard_version:Mapped[str]=mapped_column(String(40));proof_type:Mapped[str]=mapped_column(String(40));implementations:Mapped[list]=mapped_column(JSON,default=list);test_vectors:Mapped[list]=mapped_column(JSON,default=list);results:Mapped[dict]=mapped_column(JSON,default=dict);revocation_result:Mapped[dict]=mapped_column(JSON,default=dict);certificate_hash:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="failed");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class ConstitutionUpgrade(Base):
 __tablename__="constitution_upgrades";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);constitution_key:Mapped[str]=mapped_column(String(100));from_version:Mapped[str]=mapped_column(String(40));to_version:Mapped[str]=mapped_column(String(40));current_rules:Mapped[dict]=mapped_column(JSON,default=dict);proposed_rules:Mapped[dict]=mapped_column(JSON,default=dict);impact_simulation:Mapped[dict]=mapped_column(JSON,default=dict);vote:Mapped[dict]=mapped_column(JSON,default=dict);effective_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));rollback_plan:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class QuantumTransparencyArchive(Base):
 __tablename__="quantum_transparency_archives";__table_args__=(UniqueConstraint("organization_id","sequence",name="uq_quantum_archive_sequence"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);sequence:Mapped[int]=mapped_column(Integer);object_type:Mapped[str]=mapped_column(String(40));object_id:Mapped[str]=mapped_column(String(80));content_hash:Mapped[str]=mapped_column(String(64));algorithm:Mapped[str]=mapped_column(String(40));previous_root:Mapped[str]=mapped_column(String(64),default="");archive_root:Mapped[str]=mapped_column(String(64));timestamp_witnesses:Mapped[list]=mapped_column(JSON,default=list);resignatures:Mapped[list]=mapped_column(JSON,default=list);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PublicIntelligenceSignal(Base):
 __tablename__="public_intelligence_signals";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);signal_key:Mapped[str]=mapped_column(String(100));metric:Mapped[dict]=mapped_column(JSON,default=dict);sources:Mapped[list]=mapped_column(JSON,default=list);source_diversity:Mapped[float]=mapped_column(Float);allowed_purposes:Mapped[list]=mapped_column(JSON,default=list);regions:Mapped[list]=mapped_column(JSON,default=list);commitment:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="review");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class EpistemicAssessment(Base):
 __tablename__="epistemic_assessments";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);claim_id:Mapped[str]=mapped_column(String(80));evidence_graph:Mapped[dict]=mapped_column(JSON,default=dict);source_families:Mapped[dict]=mapped_column(JSON,default=dict);agent_outputs:Mapped[list]=mapped_column(JSON,default=list);narrative_signals:Mapped[dict]=mapped_column(JSON,default=dict);findings:Mapped[list]=mapped_column(JSON,default=list);risk_score:Mapped[float]=mapped_column(Float);gate_status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class AutonomousClearingBatch(Base):
 __tablename__="autonomous_clearing_batches";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);network_key:Mapped[str]=mapped_column(String(100));assets:Mapped[dict]=mapped_column(JSON,default=dict);obligations:Mapped[list]=mapped_column(JSON,default=list);prices:Mapped[dict]=mapped_column(JSON,default=dict);net_positions:Mapped[dict]=mapped_column(JSON,default=dict);liquidity_buffer:Mapped[dict]=mapped_column(JSON,default=dict);stress_result:Mapped[dict]=mapped_column(JSON,default=dict);circuit_state:Mapped[str]=mapped_column(String(20),default="closed");status:Mapped[str]=mapped_column(String(20),default="settled");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class FairResourceAllocation(Base):
 __tablename__="fair_resource_allocations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);resource_key:Mapped[str]=mapped_column(String(100));available_capacity:Mapped[float]=mapped_column(Float);requests:Mapped[list]=mapped_column(JSON,default=list);allocations:Mapped[list]=mapped_column(JSON,default=list);fairness_metrics:Mapped[dict]=mapped_column(JSON,default=dict);explanation_proof:Mapped[dict]=mapped_column(JSON,default=dict);review_status:Mapped[str]=mapped_column(String(20),default="pending");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class LongHorizonScenario(Base):
 __tablename__="long_horizon_scenarios";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));horizon_years:Mapped[int]=mapped_column(Integer);drivers:Mapped[dict]=mapped_column(JSON,default=dict);milestones:Mapped[list]=mapped_column(JSON,default=list);risk_path:Mapped[list]=mapped_column(JSON,default=list);interventions:Mapped[list]=mapped_column(JSON,default=list);replay_hash:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="completed");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class IntergenerationalCommitment(Base):
 __tablename__="intergenerational_commitments";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);commitment_key:Mapped[str]=mapped_column(String(100));beneficiaries:Mapped[list]=mapped_column(JSON,default=list);target_year:Mapped[int]=mapped_column(Integer);baseline:Mapped[dict]=mapped_column(JSON,default=dict);current_state:Mapped[dict]=mapped_column(JSON,default=dict);cost_transfers:Mapped[dict]=mapped_column(JSON,default=dict);externalities:Mapped[dict]=mapped_column(JSON,default=dict);audit_result:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="review");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class SovereignStackBuild(Base):
 __tablename__="sovereign_stack_builds";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);release_version:Mapped[str]=mapped_column(String(40));source_digest:Mapped[str]=mapped_column(String(64));build_manifest:Mapped[dict]=mapped_column(JSON,default=dict);artifact_digest:Mapped[str]=mapped_column(String(64));reproduction_digest:Mapped[str]=mapped_column(String(64));hardware_root:Mapped[dict]=mapped_column(JSON,default=dict);offline_capabilities:Mapped[list]=mapped_column(JSON,default=list);status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class SovereignStackUpgrade(Base):
 __tablename__="sovereign_stack_upgrades";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);build_id:Mapped[str]=mapped_column(ForeignKey("sovereign_stack_builds.id",ondelete="CASCADE"));from_version:Mapped[str]=mapped_column(String(40));to_version:Mapped[str]=mapped_column(String(40));package_hash:Mapped[str]=mapped_column(String(64));signature_valid:Mapped[bool]=mapped_column(Boolean,default=False);offline_test:Mapped[dict]=mapped_column(JSON,default=dict);rollback_proof:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
