"""Stage 28 global cognitive commons and self-evolving governance."""
import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,Float,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
def uid():return str(uuid.uuid4())
def now():return datetime.now(timezone.utc)
class ProofConsensusRound(Base):
 __tablename__="proof_consensus_rounds";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);proof_id:Mapped[str]=mapped_column(String(80));nodes:Mapped[list]=mapped_column(JSON,default=list);votes:Mapped[list]=mapped_column(JSON,default=list);fault_tolerance:Mapped[int]=mapped_column(Integer);decision:Mapped[str]=mapped_column(String(20));conflicts:Mapped[list]=mapped_column(JSON,default=list);consensus_hash:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="failed");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class FederatedConstitutionProtocol(Base):
 __tablename__="federated_constitution_protocols";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);action_key:Mapped[str]=mapped_column(String(100));constitutions:Mapped[list]=mapped_column(JSON,default=list);required_permission:Mapped[str]=mapped_column(String(80));compatibility:Mapped[dict]=mapped_column(JSON,default=dict);amendment:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class EvidencePreservation(Base):
 __tablename__="evidence_preservations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);archive_id:Mapped[str]=mapped_column(ForeignKey("quantum_transparency_archives.id",ondelete="RESTRICT"));retired_algorithm:Mapped[str]=mapped_column(String(40));new_algorithm:Mapped[str]=mapped_column(String(40));previous_proof:Mapped[dict]=mapped_column(JSON,default=dict);timestamp_witnesses:Mapped[list]=mapped_column(JSON,default=list);migration_proof:Mapped[dict]=mapped_column(JSON,default=dict);joint_verification:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class CausalSignalValidation(Base):
 __tablename__="causal_signal_validations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);signal_id:Mapped[str]=mapped_column(ForeignKey("public_intelligence_signals.id",ondelete="CASCADE"));experiments:Mapped[list]=mapped_column(JSON,default=list);counterfactuals:Mapped[list]=mapped_column(JSON,default=list);regional_effects:Mapped[dict]=mapped_column(JSON,default=dict);aggregate_effect:Mapped[float]=mapped_column(Float);proof:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="review");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class DissentMarket(Base):
 __tablename__="dissent_markets";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);claim_id:Mapped[str]=mapped_column(String(80));positions:Mapped[list]=mapped_column(JSON,default=list);source_diversity:Mapped[float]=mapped_column(Float);falsifiability_score:Mapped[float]=mapped_column(Float);minority_reward_cents:Mapped[int]=mapped_column(Integer);convergence_penalty_cents:Mapped[int]=mapped_column(Integer);settlement:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="open");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class PublicTreasury(Base):
 __tablename__="public_treasuries";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);treasury_key:Mapped[str]=mapped_column(String(100));opening_cents:Mapped[int]=mapped_column(Integer);revenues:Mapped[list]=mapped_column(JSON,default=list);grants:Mapped[list]=mapped_column(JSON,default=list);expenses:Mapped[list]=mapped_column(JSON,default=list);reserve_cents:Mapped[int]=mapped_column(Integer);closing_cents:Mapped[int]=mapped_column(Integer);reconciliation:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="balanced");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class AllocationAppeal(Base):
 __tablename__="allocation_appeals";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);allocation_id:Mapped[str]=mapped_column(ForeignKey("fair_resource_allocations.id",ondelete="CASCADE"));appellant_key:Mapped[str]=mapped_column(String(100));original_proof_hash:Mapped[str]=mapped_column(String(64));blind_evidence:Mapped[list]=mapped_column(JSON,default=list);replay_result:Mapped[dict]=mapped_column(JSON,default=dict);decision:Mapped[dict]=mapped_column(JSON,default=dict);compensation_cents:Mapped[int]=mapped_column(Integer,default=0);reputation_recovery:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="decided");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class CenturyRiskScenario(Base):
 __tablename__="century_risk_scenarios";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));horizon_years:Mapped[int]=mapped_column(Integer);domains:Mapped[dict]=mapped_column(JSON,default=dict);interactions:Mapped[list]=mapped_column(JSON,default=list);risk_path:Mapped[list]=mapped_column(JSON,default=list);interventions:Mapped[list]=mapped_column(JSON,default=list);replay_hash:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="completed");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class CivilizationSafetyValve(Base):
 __tablename__="civilization_safety_valves";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);valve_key:Mapped[str]=mapped_column(String(100));capability_limits:Mapped[dict]=mapped_column(JSON,default=dict);pause_signatures:Mapped[list]=mapped_column(JSON,default=list);pause_threshold:Mapped[int]=mapped_column(Integer);degraded_capabilities:Mapped[list]=mapped_column(JSON,default=list);recovery_approvals:Mapped[list]=mapped_column(JSON,default=list);drill_evidence:Mapped[dict]=mapped_column(JSON,default=dict);state:Mapped[str]=mapped_column(String(20),default="active");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class SovereignFederatedRelease(Base):
 __tablename__="sovereign_federated_releases";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);build_id:Mapped[str]=mapped_column(ForeignKey("sovereign_stack_builds.id",ondelete="RESTRICT"));release_version:Mapped[str]=mapped_column(String(40));mirrors:Mapped[list]=mapped_column(JSON,default=list);offline_patch:Mapped[dict]=mapped_column(JSON,default=dict);node_attestations:Mapped[list]=mapped_column(JSON,default=list);compatibility:Mapped[dict]=mapped_column(JSON,default=dict);release_proof:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="blocked");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
