"""Stage 23 global coordination, continuous verification and settlement."""
import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,Float,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
def uid():return str(uuid.uuid4())
def now():return datetime.now(timezone.utc)
class FederationNode(Base):
 __tablename__="federation_nodes";__table_args__=(UniqueConstraint("organization_id","node_key",name="uq_federation_node"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);node_key:Mapped[str]=mapped_column(String(100));cloud:Mapped[str]=mapped_column(String(40));region:Mapped[str]=mapped_column(String(40));protocol_versions:Mapped[list]=mapped_column(JSON,default=list);capabilities:Mapped[list]=mapped_column(JSON,default=list);identity_issuer:Mapped[str]=mapped_column(String(300));identity_fingerprint:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="pending");last_seen_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class CapabilityNegotiation(Base):
 __tablename__="capability_negotiations";__table_args__=(UniqueConstraint("organization_id","idempotency_key",name="uq_capability_negotiation"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);local_node_id:Mapped[str]=mapped_column(ForeignKey("federation_nodes.id",ondelete="CASCADE"));remote_node_id:Mapped[str]=mapped_column(ForeignKey("federation_nodes.id",ondelete="CASCADE"));idempotency_key:Mapped[str]=mapped_column(String(160));selected_version:Mapped[str]=mapped_column(String(30),default="");agreed_capabilities:Mapped[list]=mapped_column(JSON,default=list);compatibility:Mapped[dict]=mapped_column(JSON,default=dict);identity_verified:Mapped[bool]=mapped_column(Boolean,default=False);status:Mapped[str]=mapped_column(String(20),default="pending");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ProofVerification(Base):
 __tablename__="proof_verifications";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);proof_type:Mapped[str]=mapped_column(String(40));subject_type:Mapped[str]=mapped_column(String(40));subject_id:Mapped[str]=mapped_column(String(64));expected_hash:Mapped[str]=mapped_column(String(64));observed_hash:Mapped[str]=mapped_column(String(64));signature_valid:Mapped[bool]=mapped_column(Boolean,default=False);chain_valid:Mapped[bool]=mapped_column(Boolean,default=False);attestation:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="blocked");verified_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ContractNegotiation(Base):
 __tablename__="contract_negotiations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);counterparty_organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"));proposal:Mapped[dict]=mapped_column(JSON,default=dict);constraints:Mapped[dict]=mapped_column(JSON,default=dict);counter_offer:Mapped[dict]=mapped_column(JSON,default=dict);budget_cents:Mapped[int]=mapped_column(Integer);privacy_epsilon:Mapped[float]=mapped_column(Float);status:Mapped[str]=mapped_column(String(30),default="draft");approval_run_id:Mapped[str|None]=mapped_column(ForeignKey("approval_runs.id",ondelete="SET NULL"));created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class RegulatorySubscription(Base):
 __tablename__="regulatory_subscriptions";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);pack_key:Mapped[str]=mapped_column(String(100));industry:Mapped[str]=mapped_column(String(80));regions:Mapped[list]=mapped_column(JSON,default=list);active_version:Mapped[int]=mapped_column(Integer,default=0);status:Mapped[str]=mapped_column(String(20),default="active");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class RegulatoryUpdate(Base):
 __tablename__="regulatory_updates";__table_args__=(UniqueConstraint("subscription_id","version",name="uq_regulatory_update"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);subscription_id:Mapped[str]=mapped_column(ForeignKey("regulatory_subscriptions.id",ondelete="CASCADE"));version:Mapped[int]=mapped_column(Integer);delta:Mapped[dict]=mapped_column(JSON,default=dict);conflicts:Mapped[list]=mapped_column(JSON,default=list);impact:Mapped[dict]=mapped_column(JSON,default=dict);signature:Mapped[str]=mapped_column(String(64));emergency:Mapped[bool]=mapped_column(Boolean,default=False);status:Mapped[str]=mapped_column(String(20),default="review")
class SystemicRiskSignal(Base):
 __tablename__="systemic_risk_signals";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);risk_type:Mapped[str]=mapped_column(String(50));subject_ids:Mapped[list]=mapped_column(JSON,default=list);score:Mapped[float]=mapped_column(Float);threshold:Mapped[float]=mapped_column(Float);evidence:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="open");gate_status:Mapped[str]=mapped_column(String(20),default="blocked");detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ControlObservation(Base):
 __tablename__="control_observations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);control_id:Mapped[str]=mapped_column(ForeignKey("compliance_controls.id",ondelete="CASCADE"));observed_state:Mapped[dict]=mapped_column(JSON,default=dict);expected_state:Mapped[dict]=mapped_column(JSON,default=dict);drift:Mapped[dict]=mapped_column(JSON,default=dict);remediation:Mapped[list]=mapped_column(JSON,default=list);status:Mapped[str]=mapped_column(String(20),default="healthy");observed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ArbitrationCase(Base):
 __tablename__="arbitration_cases";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);dispute_id:Mapped[str]=mapped_column(ForeignKey("marketplace_disputes.id",ondelete="CASCADE"));blind_evidence:Mapped[list]=mapped_column(JSON,default=list);reproduction:Mapped[dict]=mapped_column(JSON,default=dict);arbitrator_organization_id:Mapped[str|None]=mapped_column(ForeignKey("organizations.id",ondelete="SET NULL"));bond_cents:Mapped[int]=mapped_column(Integer,default=0);decision:Mapped[dict]=mapped_column(JSON,default=dict);reputation_recovery:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="evidence");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class FederatedEvaluation(Base):
 __tablename__="federated_evaluations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);artifact_id:Mapped[str]=mapped_column(ForeignKey("supply_artifacts.id",ondelete="RESTRICT"));participants:Mapped[list]=mapped_column(JSON,default=list);suite_version:Mapped[str]=mapped_column(String(80));aggregate_metrics:Mapped[dict]=mapped_column(JSON,default=dict);bias_summary:Mapped[dict]=mapped_column(JSON,default=dict);red_team_summary:Mapped[dict]=mapped_column(JSON,default=dict);proof:Mapped[dict]=mapped_column(JSON,default=dict);sample_retained:Mapped[bool]=mapped_column(Boolean,default=False);status:Mapped[str]=mapped_column(String(20),default="review");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class GlobalSettlement(Base):
 __tablename__="global_settlements";__table_args__=(UniqueConstraint("organization_id","external_reference",name="uq_global_settlement"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);order_id:Mapped[str]=mapped_column(ForeignKey("marketplace_orders.id",ondelete="RESTRICT"));external_reference:Mapped[str]=mapped_column(String(160));source_currency:Mapped[str]=mapped_column(String(3));target_currency:Mapped[str]=mapped_column(String(3));source_amount_cents:Mapped[int]=mapped_column(Integer);fx_rate:Mapped[float]=mapped_column(Float);locked_rate_hash:Mapped[str]=mapped_column(String(64));tax_jurisdiction:Mapped[str]=mapped_column(String(50));withholding_cents:Mapped[int]=mapped_column(Integer);escrow_cents:Mapped[int]=mapped_column(Integer);payout_cents:Mapped[int]=mapped_column(Integer);status:Mapped[str]=mapped_column(String(20),default="escrowed");reconciliation:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class CrisisRoom(Base):
 __tablename__="crisis_rooms";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));region_scope:Mapped[list]=mapped_column(JSON,default=list);classification:Mapped[str]=mapped_column(String(30));commander_organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="RESTRICT"));participants:Mapped[list]=mapped_column(JSON,default=list);status:Mapped[str]=mapped_column(String(20),default="active");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class CrisisCommand(Base):
 __tablename__="crisis_commands";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);room_id:Mapped[str]=mapped_column(ForeignKey("crisis_rooms.id",ondelete="CASCADE"));command_type:Mapped[str]=mapped_column(String(50));actor_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));classification:Mapped[str]=mapped_column(String(30));payload_hash:Mapped[str]=mapped_column(String(64));previous_hash:Mapped[str]=mapped_column(String(64),default="");chain_hash:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="issued");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
