"""Tenant-scoped multilingual intelligence and decision records."""
import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,Float,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
def uid():return str(uuid.uuid4())
def now():return datetime.now(timezone.utc)
class ContentTranslation(Base):
 __tablename__="content_translations";__table_args__=(UniqueConstraint("content_item_id","target_language",name="uq_translation_content_language"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);content_item_id:Mapped[str]=mapped_column(ForeignKey("content_items.id",ondelete="CASCADE"),index=True);source_language:Mapped[str]=mapped_column(String(16));target_language:Mapped[str]=mapped_column(String(16));translated_title:Mapped[str]=mapped_column(Text,default="");translated_body:Mapped[str]=mapped_column(Text,default="");model_name:Mapped[str]=mapped_column(String(120),default="");quality_score:Mapped[float]=mapped_column(Float,default=0);status:Mapped[str]=mapped_column(String(20),default="ready");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class GlobalNarrative(Base):
 __tablename__="global_narratives"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);workspace_id:Mapped[str|None]=mapped_column(ForeignKey("enterprise_workspaces.id",ondelete="CASCADE"),index=True);event_id:Mapped[str]=mapped_column(ForeignKey("events.id",ondelete="CASCADE"),index=True);title:Mapped[str]=mapped_column(String(400));normalized_key:Mapped[str]=mapped_column(String(400),index=True);languages:Mapped[list]=mapped_column(JSON,default=list);regions:Mapped[list]=mapped_column(JSON,default=list);content_item_ids:Mapped[list]=mapped_column(JSON,default=list);entity_ids:Mapped[list]=mapped_column(JSON,default=list);confidence:Mapped[float]=mapped_column(Float,default=0);status:Mapped[str]=mapped_column(String(20),default="detected");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class NarrativeSignal(Base):
 __tablename__="narrative_signals"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);narrative_id:Mapped[str]=mapped_column(ForeignKey("global_narratives.id",ondelete="CASCADE"),index=True);signal_type:Mapped[str]=mapped_column(String(50));severity:Mapped[str]=mapped_column(String(20),default="review");confidence:Mapped[float]=mapped_column(Float,default=0);evidence_content_ids:Mapped[list]=mapped_column(JSON,default=list);explanation:Mapped[str]=mapped_column(Text);status:Mapped[str]=mapped_column(String(20),default="requires_review");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Scenario(Base):
 __tablename__="scenarios"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);workspace_id:Mapped[str|None]=mapped_column(ForeignKey("enterprise_workspaces.id",ondelete="CASCADE"),index=True);event_id:Mapped[str]=mapped_column(ForeignKey("events.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(300));assumptions:Mapped[list]=mapped_column(JSON,default=list);impact_chain:Mapped[list]=mapped_column(JSON,default=list);risk_score:Mapped[float]=mapped_column(Float,default=0);confidence:Mapped[float]=mapped_column(Float,default=0);evidence_content_ids:Mapped[list]=mapped_column(JSON,default=list);evidence_gaps:Mapped[list]=mapped_column(JSON,default=list);model_name:Mapped[str]=mapped_column(String(120),default="");status:Mapped[str]=mapped_column(String(20),default="draft");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class DecisionRoom(Base):
 __tablename__="decision_rooms"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);workspace_id:Mapped[str|None]=mapped_column(ForeignKey("enterprise_workspaces.id",ondelete="CASCADE"),index=True);event_id:Mapped[str]=mapped_column(ForeignKey("events.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(300));status:Mapped[str]=mapped_column(String(20),default="open");frozen_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));frozen_by:Mapped[str|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class DecisionOption(Base):
 __tablename__="decision_options"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);room_id:Mapped[str]=mapped_column(ForeignKey("decision_rooms.id",ondelete="CASCADE"),index=True);title:Mapped[str]=mapped_column(String(300));constraints:Mapped[list]=mapped_column(JSON,default=list);benefits:Mapped[list]=mapped_column(JSON,default=list);side_effects:Mapped[list]=mapped_column(JSON,default=list);counterfactuals:Mapped[list]=mapped_column(JSON,default=list);red_team_questions:Mapped[list]=mapped_column(JSON,default=list);evidence_content_ids:Mapped[list]=mapped_column(JSON,default=list);confidence:Mapped[float]=mapped_column(Float,default=0);status:Mapped[str]=mapped_column(String(20),default="draft");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class DecisionAudit(Base):
 __tablename__="decision_audits"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);room_id:Mapped[str]=mapped_column(ForeignKey("decision_rooms.id",ondelete="CASCADE"),index=True);actor_id:Mapped[str|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));action:Mapped[str]=mapped_column(String(80));details:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
