"""Tenant-scoped multimodal evidence, live intelligence and collaboration records."""
import uuid
from datetime import datetime,timezone
from sqlalchemy import BigInteger,Boolean,DateTime,Float,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base

def uid():return str(uuid.uuid4())
def now():return datetime.now(timezone.utc)

class MediaAsset(Base):
 __tablename__="media_assets";__table_args__=(UniqueConstraint("organization_id","content_hash",name="uq_media_tenant_hash"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);workspace_id:Mapped[str|None]=mapped_column(ForeignKey("enterprise_workspaces.id",ondelete="CASCADE"),index=True);user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"),index=True);filename:Mapped[str]=mapped_column(String(300));media_type:Mapped[str]=mapped_column(String(20),index=True);mime_type:Mapped[str]=mapped_column(String(100));byte_size:Mapped[int]=mapped_column(BigInteger);content_hash:Mapped[str]=mapped_column(String(64),index=True);perceptual_hash:Mapped[str]=mapped_column(String(64),default="");duplicate_of_id:Mapped[str|None]=mapped_column(ForeignKey("media_assets.id",ondelete="SET NULL"));storage_key:Mapped[str]=mapped_column(String(1000));status:Mapped[str]=mapped_column(String(20),default="queued",index=True);duration_ms:Mapped[int|None]=mapped_column(BigInteger);width:Mapped[int|None]=mapped_column(Integer);height:Mapped[int|None]=mapped_column(Integer);language:Mapped[str]=mapped_column(String(20),default="");copyright_status:Mapped[str]=mapped_column(String(20),default="unknown");license_name:Mapped[str]=mapped_column(String(120),default="");source_url:Mapped[str]=mapped_column(String(1000),default="");consent_confirmed:Mapped[bool]=mapped_column(Boolean,default=False);safety_status:Mapped[str]=mapped_column(String(20),default="pending");safety_findings:Mapped[list]=mapped_column(JSON,default=list);error_message:Mapped[str]=mapped_column(Text,default="");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class MediaProcessingRun(Base):
 __tablename__="media_processing_runs"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);asset_id:Mapped[str]=mapped_column(ForeignKey("media_assets.id",ondelete="CASCADE"),index=True);status:Mapped[str]=mapped_column(String(20),default="queued",index=True);stage:Mapped[str]=mapped_column(String(40),default="security_scan");progress:Mapped[int]=mapped_column(Integer,default=0);attempt:Mapped[int]=mapped_column(Integer,default=1);model_routes:Mapped[dict]=mapped_column(JSON,default=dict);estimated_cost_cents:Mapped[int]=mapped_column(Integer,default=0);actual_cost_cents:Mapped[int]=mapped_column(Integer,default=0);error_message:Mapped[str]=mapped_column(Text,default="");lease_owner:Mapped[str|None]=mapped_column(String(100));lease_until:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class MediaEvidence(Base):
 __tablename__="media_evidence";__table_args__=(UniqueConstraint("asset_id","ordinal",name="uq_media_evidence_ordinal"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);asset_id:Mapped[str]=mapped_column(ForeignKey("media_assets.id",ondelete="CASCADE"),index=True);ordinal:Mapped[int]=mapped_column(Integer);evidence_type:Mapped[str]=mapped_column(String(30));text:Mapped[str]=mapped_column(Text,default="");start_ms:Mapped[int|None]=mapped_column(BigInteger);end_ms:Mapped[int|None]=mapped_column(BigInteger);frame_number:Mapped[int|None]=mapped_column(BigInteger);bbox:Mapped[list]=mapped_column(JSON,default=list);speaker:Mapped[str]=mapped_column(String(80),default="");confidence:Mapped[float]=mapped_column(Float,default=0);storage_key:Mapped[str]=mapped_column(String(1000),default="");metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict);content_hash:Mapped[str]=mapped_column(String(64),index=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class MediaCitation(Base):
 __tablename__="media_citations"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);evidence_id:Mapped[str]=mapped_column(ForeignKey("media_evidence.id",ondelete="CASCADE"),index=True);target_type:Mapped[str]=mapped_column(String(30));target_id:Mapped[str]=mapped_column(String(36),index=True);claim_index:Mapped[int]=mapped_column(Integer,default=0);quote:Mapped[str]=mapped_column(String(1000));locator:Mapped[dict]=mapped_column(JSON);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class LiveStream(Base):
 __tablename__="live_streams"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);workspace_id:Mapped[str|None]=mapped_column(ForeignKey("enterprise_workspaces.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(160));source_type:Mapped[str]=mapped_column(String(20),default="field");source_url:Mapped[str]=mapped_column(String(1000),default="");status:Mapped[str]=mapped_column(String(20),default="live",index=True);created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);ended_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class LiveUpdate(Base):
 __tablename__="live_updates";__table_args__=(UniqueConstraint("stream_id","sequence",name="uq_live_update_sequence"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);stream_id:Mapped[str]=mapped_column(ForeignKey("live_streams.id",ondelete="CASCADE"),index=True);sequence:Mapped[int]=mapped_column(BigInteger);update_type:Mapped[str]=mapped_column(String(30));payload:Mapped[dict]=mapped_column(JSON);asset_id:Mapped[str|None]=mapped_column(ForeignKey("media_assets.id",ondelete="SET NULL"));occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class CollaborativeDocument(Base):
 __tablename__="collaborative_documents";__table_args__=(UniqueConstraint("organization_id","resource_type","resource_id",name="uq_collab_resource"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);workspace_id:Mapped[str|None]=mapped_column(ForeignKey("enterprise_workspaces.id",ondelete="CASCADE"),index=True);resource_type:Mapped[str]=mapped_column(String(20));resource_id:Mapped[str]=mapped_column(String(36),index=True);version:Mapped[int]=mapped_column(Integer,default=1);snapshot:Mapped[dict]=mapped_column(JSON,default=dict);snapshot_hash:Mapped[str]=mapped_column(String(64));updated_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class CollaborativeChange(Base):
 __tablename__="collaborative_changes";__table_args__=(UniqueConstraint("document_id","client_id","client_sequence",name="uq_collab_client_sequence"),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);document_id:Mapped[str]=mapped_column(ForeignKey("collaborative_documents.id",ondelete="CASCADE"),index=True);base_version:Mapped[int]=mapped_column(Integer);result_version:Mapped[int|None]=mapped_column(Integer);client_id:Mapped[str]=mapped_column(String(80));client_sequence:Mapped[int]=mapped_column(BigInteger);operations:Mapped[list]=mapped_column(JSON);changed_paths:Mapped[list]=mapped_column(JSON);status:Mapped[str]=mapped_column(String(20),default="applied",index=True);conflict:Mapped[dict]=mapped_column(JSON,default=dict);created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class CollaborationComment(Base):
 __tablename__="collaboration_comments"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);document_id:Mapped[str]=mapped_column(ForeignKey("collaborative_documents.id",ondelete="CASCADE"),index=True);parent_id:Mapped[str|None]=mapped_column(ForeignKey("collaboration_comments.id",ondelete="CASCADE"));user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));body:Mapped[str]=mapped_column(Text);anchor:Mapped[dict]=mapped_column(JSON,default=dict);mention_user_ids:Mapped[list]=mapped_column(JSON,default=list);status:Mapped[str]=mapped_column(String(20),default="open");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class CollaborationTicket(Base):
 __tablename__="collaboration_tickets"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);document_id:Mapped[str]=mapped_column(ForeignKey("collaborative_documents.id",ondelete="CASCADE"),index=True);user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"));ticket_hash:Mapped[str]=mapped_column(String(64),unique=True);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));consumed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class CollaborationAudit(Base):
 __tablename__="collaboration_audits"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);document_id:Mapped[str|None]=mapped_column(ForeignKey("collaborative_documents.id",ondelete="SET NULL"),index=True);actor_id:Mapped[str|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));action:Mapped[str]=mapped_column(String(80),index=True);details:Mapped[dict]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
