"""Stage 22 federated trust network, provenance and marketplace records."""
import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,Float,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
def uid():return str(uuid.uuid4())
def now():return datetime.now(timezone.utc)
class FederationAgreement(Base):
 __tablename__="federation_agreements";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);partner_organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);purpose:Mapped[str]=mapped_column(String(120));allowed_metrics:Mapped[list]=mapped_column(JSON,default=list);regions:Mapped[list]=mapped_column(JSON,default=list);minimum_cohort:Mapped[int]=mapped_column(Integer,default=10);status:Mapped[str]=mapped_column(String(20),default="active");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ExchangeEnvelope(Base):
 __tablename__="federation_envelopes";__table_args__=(UniqueConstraint("organization_id","idempotency_key",name="uq_federation_envelope"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);agreement_id:Mapped[str]=mapped_column(ForeignKey("federation_agreements.id",ondelete="RESTRICT"));recipient_organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"));metric_key:Mapped[str]=mapped_column(String(100));aggregate:Mapped[dict]=mapped_column(JSON,default=dict);evidence_summary:Mapped[dict]=mapped_column(JSON,default=dict);privacy:Mapped[dict]=mapped_column(JSON,default=dict);idempotency_key:Mapped[str]=mapped_column(String(160));signature:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(20),default="available");withdrawn_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ProvenanceNode(Base):
 __tablename__="provenance_nodes";__table_args__=(UniqueConstraint("organization_id","object_type","object_id",name="uq_provenance_object"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);object_type:Mapped[str]=mapped_column(String(40));object_id:Mapped[str]=mapped_column(String(64));version:Mapped[str]=mapped_column(String(80),default="");content_hash:Mapped[str]=mapped_column(String(64));signature:Mapped[str]=mapped_column(String(64));metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ProvenanceEdge(Base):
 __tablename__="provenance_edges";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);source_node_id:Mapped[str]=mapped_column(ForeignKey("provenance_nodes.id",ondelete="CASCADE"));target_node_id:Mapped[str]=mapped_column(ForeignKey("provenance_nodes.id",ondelete="CASCADE"));relation:Mapped[str]=mapped_column(String(50));evidence_hash:Mapped[str]=mapped_column(String(64));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class DataContract(Base):
 __tablename__="data_contracts";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);dataset_key:Mapped[str]=mapped_column(String(100));purpose:Mapped[str]=mapped_column(String(120));allowed_uses:Mapped[list]=mapped_column(JSON,default=list);regions:Mapped[list]=mapped_column(JSON,default=list);derivative_rights:Mapped[str]=mapped_column(String(30),default="restricted");expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));status:Mapped[str]=mapped_column(String(20),default="active");withdrawal_generation:Mapped[int]=mapped_column(Integer,default=0);created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class SupplyArtifact(Base):
 __tablename__="supply_artifacts";__table_args__=(UniqueConstraint("organization_id","artifact_type","key","version",name="uq_supply_artifact"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);artifact_type:Mapped[str]=mapped_column(String(30));key:Mapped[str]=mapped_column(String(100));version:Mapped[str]=mapped_column(String(80));manifest:Mapped[dict]=mapped_column(JSON,default=dict);sbom:Mapped[list]=mapped_column(JSON,default=list);vendor_risk:Mapped[float]=mapped_column(Float,default=0);signature:Mapped[str]=mapped_column(String(64));attestation:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="review");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class IntelligenceProduct(Base):
 __tablename__="intelligence_products";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);key:Mapped[str]=mapped_column(String(100));name:Mapped[str]=mapped_column(String(180));description:Mapped[str]=mapped_column(Text,default="");license_terms:Mapped[dict]=mapped_column(JSON,default=dict);quality_sla:Mapped[dict]=mapped_column(JSON,default=dict);price_cents:Mapped[int]=mapped_column(Integer);currency:Mapped[str]=mapped_column(String(3),default="CNY");revenue_share_percent:Mapped[float]=mapped_column(Float,default=80);status:Mapped[str]=mapped_column(String(20),default="draft");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));__table_args__=(UniqueConstraint("organization_id","key",name="uq_intelligence_product"),)
class MarketplaceOrder(Base):
 __tablename__="marketplace_orders";__table_args__=(UniqueConstraint("buyer_organization_id","idempotency_key",name="uq_market_order"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);buyer_organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);product_id:Mapped[str]=mapped_column(ForeignKey("intelligence_products.id",ondelete="RESTRICT"));idempotency_key:Mapped[str]=mapped_column(String(160));amount_cents:Mapped[int]=mapped_column(Integer);currency:Mapped[str]=mapped_column(String(3));status:Mapped[str]=mapped_column(String(30),default="authorized");provider_reference:Mapped[str]=mapped_column(String(160),default="");delivery_receipt:Mapped[dict]=mapped_column(JSON,default=dict);settlement:Mapped[dict]=mapped_column(JSON,default=dict);created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class MarketplaceDispute(Base):
 __tablename__="marketplace_disputes";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);order_id:Mapped[str]=mapped_column(ForeignKey("marketplace_orders.id",ondelete="CASCADE"));reason:Mapped[str]=mapped_column(String(500));status:Mapped[str]=mapped_column(String(20),default="open");resolution:Mapped[dict]=mapped_column(JSON,default=dict);created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class FederatedComputation(Base):
 __tablename__="federated_computations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);agreement_id:Mapped[str]=mapped_column(ForeignKey("federation_agreements.id",ondelete="RESTRICT"));computation_type:Mapped[str]=mapped_column(String(40));participants:Mapped[list]=mapped_column(JSON,default=list);privacy_allocation:Mapped[dict]=mapped_column(JSON,default=dict);attestation:Mapped[dict]=mapped_column(JSON,default=dict);result:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="planned");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class ResponsibilityEvent(Base):
 __tablename__="responsibility_events";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);subject_type:Mapped[str]=mapped_column(String(40));subject_id:Mapped[str]=mapped_column(String(64));event_type:Mapped[str]=mapped_column(String(40));actor_id:Mapped[str|None]=mapped_column(ForeignKey("users.id",ondelete="SET NULL"));payload_hash:Mapped[str]=mapped_column(String(64));previous_hash:Mapped[str]=mapped_column(String(64),default="");chain_hash:Mapped[str]=mapped_column(String(64));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class RegulatoryPack(Base):
 __tablename__="regulatory_packs";__table_args__=(UniqueConstraint("organization_id","key","version",name="uq_regulatory_pack"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);key:Mapped[str]=mapped_column(String(100));version:Mapped[int]=mapped_column(Integer);industry:Mapped[str]=mapped_column(String(80));region:Mapped[str]=mapped_column(String(40));rules:Mapped[dict]=mapped_column(JSON,default=dict);signature:Mapped[str]=mapped_column(String(64));rollback_of_version:Mapped[int|None]=mapped_column(Integer);status:Mapped[str]=mapped_column(String(20),default="draft");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"))
class TrustScore(Base):
 __tablename__="trust_scores";__table_args__=(UniqueConstraint("organization_id","subject_type","subject_id",name="uq_trust_subject"),);id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);subject_type:Mapped[str]=mapped_column(String(30));subject_id:Mapped[str]=mapped_column(String(64));quality:Mapped[float]=mapped_column(Float,default=0);reliability:Mapped[float]=mapped_column(Float,default=0);abuse_penalty:Mapped[float]=mapped_column(Float,default=0);score:Mapped[float]=mapped_column(Float,default=0);status:Mapped[str]=mapped_column(String(20),default="review")
class AbuseReport(Base):
 __tablename__="abuse_reports";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);subject_type:Mapped[str]=mapped_column(String(30));subject_id:Mapped[str]=mapped_column(String(64));category:Mapped[str]=mapped_column(String(50));evidence:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(20),default="open");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class EcosystemDrill(Base):
 __tablename__="ecosystem_drills";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);organization_id:Mapped[str]=mapped_column(ForeignKey("organizations.id",ondelete="CASCADE"),index=True);scenario:Mapped[str]=mapped_column(String(60));participants:Mapped[list]=mapped_column(JSON,default=list);expected_controls:Mapped[list]=mapped_column(JSON,default=list);evidence:Mapped[dict]=mapped_column(JSON,default=dict);containment_minutes:Mapped[int|None]=mapped_column(Integer);recovery_minutes:Mapped[int|None]=mapped_column(Integer);status:Mapped[str]=mapped_column(String(20),default="planned");created_by:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
