import request from './request'
const key='infopulse-enterprise-context'
function config(extra:any={}){let v:any={};try{v=JSON.parse(sessionStorage.getItem(key)||'{}')}catch{}return{...extra,headers:{...(extra.headers||{}),...(v.organizationId?{'X-Organization-ID':v.organizationId}:{}),...(v.workspaceId?{'X-Workspace-ID':v.workspaceId}:{})}}}
export const multimodalApi={
 capabilities:async()=>(await request.get('/multimodal/capabilities',config())).data,assets:async()=>(await request.get('/multimodal/assets',config())).data,asset:async(id:string)=>(await request.get(`/multimodal/assets/${id}`,config())).data,
 upload:async(data:FormData)=>(await request.post('/multimodal/assets',data,config({headers:{'Content-Type':'multipart/form-data'},timeout:120000}))).data,content:async(path:string)=>URL.createObjectURL((await request.get(path.replace('/api/v1',''),config({responseType:'blob'}))).data),
 retry:(id:string)=>request.post(`/multimodal/assets/${id}/retry`,{},config()),remove:(id:string)=>request.delete(`/multimodal/assets/${id}`,config()),safety:(id:string,data:any)=>request.post(`/multimodal/assets/${id}/safety`,data,config()),cite:(id:string,data:any)=>request.post(`/multimodal/evidence/${id}/citations`,data,config()),
 streams:async()=>(await request.get('/multimodal/live',config())).data,createStream:async(data:any)=>(await request.post('/multimodal/live',data,config())).data,updates:async(id:string,after=0)=>(await request.get(`/multimodal/live/${id}/updates?after=${after}`,config())).data,addUpdate:(id:string,data:any)=>request.post(`/multimodal/live/${id}/updates`,data,config()),end:(id:string)=>request.post(`/multimodal/live/${id}/end`,{},config()),
 openDoc:async(data:any)=>(await request.post('/multimodal/collaboration/documents',data,config())).data,doc:async(id:string)=>(await request.get(`/multimodal/collaboration/documents/${id}`,config())).data,change:async(id:string,data:any)=>(await request.post(`/multimodal/collaboration/documents/${id}/changes`,data,config())).data,resolve:(id:string,data:any)=>request.post(`/multimodal/collaboration/changes/${id}/resolve`,data,config()),comment:(id:string,data:any)=>request.post(`/multimodal/collaboration/documents/${id}/comments`,data,config()),ticket:async(id:string)=>(await request.post(`/multimodal/collaboration/documents/${id}/ticket`,{},config())).data,
}
