import request from './request'
const key='infopulse-enterprise-context';function config(){let v:any={};try{v=JSON.parse(sessionStorage.getItem(key)||'{}')}catch{}return{headers:{...(v.organizationId?{'X-Organization-ID':v.organizationId}:{}),...(v.workspaceId?{'X-Workspace-ID':v.workspaceId}:{})}}}
export const orchestrationApi={
 overview:async()=>(await request.get('/orchestration/overview',config())).data,tools:async()=>(await request.get('/orchestration/tools',config())).data,policy:(data:any)=>request.put('/orchestration/tool-policies',data,config()),
 prompts:async()=>(await request.get('/orchestration/prompts',config())).data,createPrompt:(data:any)=>request.post('/orchestration/prompts',data,config()),routes:async()=>(await request.get('/orchestration/model-routes',config())).data,saveRoute:(data:any)=>request.put('/orchestration/model-routes',data,config()),
 workflows:async()=>(await request.get('/orchestration/workflows',config())).data,createWorkflow:async(data:any)=>(await request.post('/orchestration/workflows',data,config())).data,workflow:async(id:string)=>(await request.get(`/orchestration/workflows/${id}`,config())).data,version:(id:string,data:any)=>request.post(`/orchestration/workflows/${id}/versions`,data,config()),activate:(id:string,version:string)=>request.post(`/orchestration/workflows/${id}/activate/${version}`,{},config()),
 runs:async()=>(await request.get('/orchestration/runs',config())).data,start:async(id:string,data:any)=>(await request.post(`/orchestration/workflows/${id}/runs`,data,config())).data,run:async(id:string)=>(await request.get(`/orchestration/runs/${id}`,config())).data,advance:(id:string)=>request.post(`/orchestration/runs/${id}/advance`,{},config()),cancel:(id:string)=>request.post(`/orchestration/runs/${id}/cancel`,{},config()),replay:(id:string)=>request.post(`/orchestration/runs/${id}/replay`,{},config()),
 approvals:async()=>(await request.get('/orchestration/approvals',config())).data,decide:(id:string,data:any)=>request.post(`/orchestration/approvals/${id}/decision`,data,config()),
 memories:async()=>(await request.get('/orchestration/memories',config())).data,putMemory:(data:any)=>request.put('/orchestration/memories',data,config()),deleteMemory:(id:string)=>request.delete(`/orchestration/memories/${id}`,config()),
 datasets:async()=>(await request.get('/orchestration/evaluations/datasets',config())).data,createDataset:async(data:any)=>(await request.post('/orchestration/evaluations/datasets',data,config())).data,evaluate:async(dataset:string,version:string)=>(await request.post(`/orchestration/evaluations/datasets/${dataset}/run/${version}`,{},config())).data,
 templates:async()=>(await request.get('/orchestration/templates',config())).data,createTemplate:(data:any)=>request.post('/orchestration/templates',data,config()),install:(id:string)=>request.post(`/orchestration/templates/${id}/install`,{},config()),
}
