"""Add tenant open platform and ecosystem integration records.

Revision ID: 20260730_0016
Revises: 20260729_0015
"""
from alembic import op
import sqlalchemy as sa

revision = "20260730_0016"
down_revision = "20260729_0015"
branch_labels = None
depends_on = None


def tenant_table(name, *columns, constraints=()):
    op.create_table(name, sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), *columns, *constraints)
    op.create_index(f"ix_{name}_organization_id", name, ["organization_id"])


def upgrade():
    tenant_table("developer_api_keys", sa.Column("workspace_id", sa.String(36), sa.ForeignKey("enterprise_workspaces.id", ondelete="CASCADE")), sa.Column("name", sa.String(120), nullable=False), sa.Column("key_prefix", sa.String(16), nullable=False, unique=True), sa.Column("key_hash", sa.String(64), nullable=False, unique=True), sa.Column("scopes", sa.JSON(), nullable=False), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("last_used_at", sa.DateTime(timezone=True)), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    tenant_table("oauth_applications", sa.Column("name", sa.String(120), nullable=False), sa.Column("client_id", sa.String(64), nullable=False, unique=True), sa.Column("client_secret_hash", sa.String(64), nullable=False), sa.Column("app_type", sa.String(16), nullable=False), sa.Column("redirect_uris", sa.JSON(), nullable=False), sa.Column("scopes", sa.JSON(), nullable=False), sa.Column("review_status", sa.String(20), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    tenant_table("oauth_authorization_codes", sa.Column("application_id", sa.String(36), sa.ForeignKey("oauth_applications.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("code_hash", sa.String(64), nullable=False, unique=True), sa.Column("redirect_uri", sa.String(1000), nullable=False), sa.Column("scopes", sa.JSON(), nullable=False), sa.Column("code_challenge", sa.String(128), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("consumed_at", sa.DateTime(timezone=True)))
    tenant_table("oauth_access_grants", sa.Column("application_id", sa.String(36), sa.ForeignKey("oauth_applications.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("access_token_hash", sa.String(64), nullable=False, unique=True), sa.Column("refresh_token_hash", sa.String(64), nullable=False, unique=True), sa.Column("scopes", sa.JSON(), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)))
    tenant_table("webhook_endpoints", sa.Column("workspace_id", sa.String(36), sa.ForeignKey("enterprise_workspaces.id", ondelete="CASCADE")), sa.Column("name", sa.String(120), nullable=False), sa.Column("target_url", sa.String(1000), nullable=False), sa.Column("event_types", sa.JSON(), nullable=False), sa.Column("secret_hash", sa.String(64), nullable=False), sa.Column("secret_ciphertext", sa.Text(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    tenant_table("webhook_deliveries", sa.Column("endpoint_id", sa.String(36), sa.ForeignKey("webhook_endpoints.id", ondelete="CASCADE"), nullable=False), sa.Column("event_id", sa.String(64), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("fingerprint", sa.String(64), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("attempt", sa.Integer(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("response_code", sa.Integer()), sa.Column("error", sa.String(1000), nullable=False), sa.Column("replay_of_id", sa.String(36), sa.ForeignKey("webhook_deliveries.id", ondelete="SET NULL")), sa.Column("next_attempt_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("delivered_at", sa.DateTime(timezone=True)), constraints=(sa.UniqueConstraint("endpoint_id", "fingerprint", "attempt", name="uq_webhook_delivery_attempt"),))
    op.create_table("connector_definitions", sa.Column("key", sa.String(40), primary_key=True), sa.Column("name", sa.String(80), nullable=False), sa.Column("category", sa.String(30), nullable=False), sa.Column("capabilities", sa.JSON(), nullable=False), sa.Column("required_scopes", sa.JSON(), nullable=False), sa.Column("write_capable", sa.Boolean(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False))
    tenant_table("connector_installations", sa.Column("workspace_id", sa.String(36), sa.ForeignKey("enterprise_workspaces.id", ondelete="CASCADE")), sa.Column("connector_key", sa.String(40), sa.ForeignKey("connector_definitions.key", ondelete="RESTRICT"), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("credential_reference", sa.String(500), nullable=False), sa.Column("config", sa.JSON(), nullable=False), sa.Column("requested_by", sa.String(36), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("approved_by", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), constraints=(sa.UniqueConstraint("organization_id", "workspace_id", "connector_key", name="uq_connector_installation"),))
    tenant_table("platform_security_reviews", sa.Column("target_type", sa.String(30), nullable=False), sa.Column("target_id", sa.String(64), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("findings", sa.JSON(), nullable=False), sa.Column("reviewed_by", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("reviewed_at", sa.DateTime(timezone=True)))
    op.create_table("platform_plans", sa.Column("key", sa.String(30), primary_key=True), sa.Column("name", sa.String(80), nullable=False), sa.Column("monthly_request_limit", sa.BigInteger(), nullable=False), sa.Column("overage_allowed", sa.Boolean(), nullable=False), sa.Column("unit_price_cents", sa.Integer(), nullable=False))
    op.create_table("platform_billing_accounts", sa.Column("organization_id", sa.String(36), sa.ForeignKey("organizations.id", ondelete="CASCADE"), primary_key=True), sa.Column("plan_key", sa.String(30), sa.ForeignKey("platform_plans.key"), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("overage_enabled", sa.Boolean(), nullable=False), sa.Column("billing_reference", sa.String(500), nullable=False))
    tenant_table("api_usage_meters", sa.Column("workspace_id", sa.String(36), sa.ForeignKey("enterprise_workspaces.id", ondelete="CASCADE")), sa.Column("period", sa.String(7), nullable=False), sa.Column("scope", sa.String(80), nullable=False), sa.Column("requests", sa.BigInteger(), nullable=False), sa.Column("billable_units", sa.BigInteger(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), constraints=(sa.UniqueConstraint("organization_id", "workspace_id", "period", "scope", name="uq_api_usage_meter"),))
    if op.get_bind().dialect.name == "postgresql":
        for table in ("developer_api_keys", "oauth_applications", "oauth_authorization_codes", "oauth_access_grants", "webhook_endpoints", "webhook_deliveries", "connector_installations", "platform_security_reviews", "platform_billing_accounts", "api_usage_meters"):
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {table}_tenant_policy ON {table} USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))")


def downgrade():
    for table in ("api_usage_meters", "platform_billing_accounts", "platform_plans", "platform_security_reviews", "connector_installations", "connector_definitions", "webhook_deliveries", "webhook_endpoints", "oauth_access_grants", "oauth_authorization_codes", "oauth_applications", "developer_api_keys"):
        op.drop_table(table)
