"""Add subscriptions, scheduled tasks, runs, notifications and deliveries."""

from alembic import op
import sqlalchemy as sa

revision = "20260728_0009"
down_revision = "20260728_0008"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("subscriptions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("target_type", sa.String(30), nullable=False), sa.Column("target_id", sa.String(36)), sa.Column("query", sa.String(500), nullable=False), sa.Column("filters", sa.JSON(), nullable=False), sa.Column("schedule", sa.JSON(), nullable=False), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("channels", sa.JSON(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("task_id", sa.String(36)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_subscriptions_user_id", "subscriptions", ["user_id"]); op.create_index("ix_subscriptions_target_id", "subscriptions", ["target_id"]); op.create_index("ix_subscriptions_task_id", "subscriptions", ["task_id"])
    op.create_table("agent_tasks", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("subscription_id", sa.String(36), sa.ForeignKey("subscriptions.id", ondelete="SET NULL")), sa.Column("name", sa.String(200), nullable=False), sa.Column("task_type", sa.String(40), nullable=False), sa.Column("config", sa.JSON(), nullable=False), sa.Column("schedule", sa.JSON(), nullable=False), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("max_retries", sa.Integer(), nullable=False), sa.Column("max_concurrency", sa.Integer(), nullable=False), sa.Column("cost_limit", sa.Float(), nullable=False), sa.Column("estimated_cost", sa.Float(), nullable=False), sa.Column("high_risk", sa.Boolean(), nullable=False), sa.Column("confirmation_status", sa.String(20), nullable=False), sa.Column("next_run_at", sa.DateTime(timezone=True)), sa.Column("last_run_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    for column in ("user_id", "subscription_id", "status", "next_run_at"): op.create_index(f"ix_agent_tasks_{column}", "agent_tasks", [column])
    op.create_table("task_runs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("task_id", sa.String(36), sa.ForeignKey("agent_tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("idempotency_key", sa.String(200), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("attempt", sa.Integer(), nullable=False), sa.Column("trigger", sa.String(20), nullable=False), sa.Column("scheduled_for", sa.DateTime(timezone=True)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("retry_at", sa.DateTime(timezone=True)), sa.Column("output", sa.JSON(), nullable=False), sa.Column("logs", sa.JSON(), nullable=False), sa.Column("error_message", sa.Text(), nullable=False), sa.Column("diagnostic_id", sa.String(36), nullable=False), sa.Column("cost", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("idempotency_key", name="uq_task_run_idempotency"))
    for column in ("task_id", "user_id", "status", "retry_at"): op.create_index(f"ix_task_runs_{column}", "task_runs", [column])
    op.create_table("notifications", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("notification_type", sa.String(30), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("body", sa.Text(), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("group_key", sa.String(200), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("scheduled_delivery_at", sa.DateTime(timezone=True)), sa.Column("read_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    for column in ("user_id", "notification_type", "status", "group_key", "scheduled_delivery_at", "created_at"): op.create_index(f"ix_notifications_{column}", "notifications", [column])
    op.create_table("notification_preferences", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("quiet_hours_enabled", sa.Boolean(), nullable=False), sa.Column("quiet_start", sa.String(5), nullable=False), sa.Column("quiet_end", sa.String(5), nullable=False), sa.Column("digest_enabled", sa.Boolean(), nullable=False), sa.Column("email_enabled", sa.Boolean(), nullable=False), sa.Column("email_address", sa.String(320), nullable=False), sa.Column("webhook_enabled", sa.Boolean(), nullable=False), sa.Column("webhook_url", sa.String(1000), nullable=False), sa.Column("webhook_secret", sa.String(300), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("user_id", name="uq_notification_preference_user"))
    op.create_index("ix_notification_preferences_user_id", "notification_preferences", ["user_id"])
    op.create_table("delivery_attempts", sa.Column("id", sa.String(36), primary_key=True), sa.Column("notification_id", sa.String(36), sa.ForeignKey("notifications.id", ondelete="CASCADE"), nullable=False), sa.Column("channel", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("attempt", sa.Integer(), nullable=False), sa.Column("response_code", sa.Integer()), sa.Column("error_message", sa.Text(), nullable=False), sa.Column("next_retry_at", sa.DateTime(timezone=True)), sa.Column("delivered_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    for column in ("notification_id", "status", "next_retry_at"): op.create_index(f"ix_delivery_attempts_{column}", "delivery_attempts", [column])


def downgrade():
    for table in ("delivery_attempts", "notification_preferences", "notifications", "task_runs", "agent_tasks", "subscriptions"):
        op.drop_table(table)
