"""Add multimodal evidence and real-time collaboration.

Revision ID: 20260730_0018
Revises: 20260730_0017
"""
from alembic import op
import sqlalchemy as sa
revision="20260730_0018";down_revision="20260730_0017";branch_labels=None;depends_on=None
def tenant(name,*cols,constraints=()):
 op.create_table(name,sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),*cols,*constraints);op.create_index(f"ix_{name}_organization_id",name,["organization_id"])
def upgrade():
 tenant("media_assets",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("filename",sa.String(300),nullable=False),sa.Column("media_type",sa.String(20),nullable=False),sa.Column("mime_type",sa.String(100),nullable=False),sa.Column("byte_size",sa.BigInteger(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("perceptual_hash",sa.String(64),nullable=False),sa.Column("duplicate_of_id",sa.String(36),sa.ForeignKey("media_assets.id",ondelete="SET NULL")),sa.Column("storage_key",sa.String(1000),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("duration_ms",sa.BigInteger()),sa.Column("width",sa.Integer()),sa.Column("height",sa.Integer()),sa.Column("language",sa.String(20),nullable=False),sa.Column("copyright_status",sa.String(20),nullable=False),sa.Column("license_name",sa.String(120),nullable=False),sa.Column("source_url",sa.String(1000),nullable=False),sa.Column("consent_confirmed",sa.Boolean(),nullable=False),sa.Column("safety_status",sa.String(20),nullable=False),sa.Column("safety_findings",sa.JSON(),nullable=False),sa.Column("error_message",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)),constraints=(sa.UniqueConstraint("organization_id","content_hash",name="uq_media_tenant_hash"),))
 tenant("media_processing_runs",sa.Column("asset_id",sa.String(36),sa.ForeignKey("media_assets.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("stage",sa.String(40),nullable=False),sa.Column("progress",sa.Integer(),nullable=False),sa.Column("attempt",sa.Integer(),nullable=False),sa.Column("model_routes",sa.JSON(),nullable=False),sa.Column("estimated_cost_cents",sa.Integer(),nullable=False),sa.Column("actual_cost_cents",sa.Integer(),nullable=False),sa.Column("error_message",sa.Text(),nullable=False),sa.Column("lease_owner",sa.String(100)),sa.Column("lease_until",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)))
 tenant("media_evidence",sa.Column("asset_id",sa.String(36),sa.ForeignKey("media_assets.id",ondelete="CASCADE"),nullable=False),sa.Column("ordinal",sa.Integer(),nullable=False),sa.Column("evidence_type",sa.String(30),nullable=False),sa.Column("text",sa.Text(),nullable=False),sa.Column("start_ms",sa.BigInteger()),sa.Column("end_ms",sa.BigInteger()),sa.Column("frame_number",sa.BigInteger()),sa.Column("bbox",sa.JSON(),nullable=False),sa.Column("speaker",sa.String(80),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("storage_key",sa.String(1000),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("asset_id","ordinal",name="uq_media_evidence_ordinal"),))
 tenant("media_citations",sa.Column("evidence_id",sa.String(36),sa.ForeignKey("media_evidence.id",ondelete="CASCADE"),nullable=False),sa.Column("target_type",sa.String(30),nullable=False),sa.Column("target_id",sa.String(36),nullable=False),sa.Column("claim_index",sa.Integer(),nullable=False),sa.Column("quote",sa.String(1000),nullable=False),sa.Column("locator",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 tenant("live_streams",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("name",sa.String(160),nullable=False),sa.Column("source_type",sa.String(20),nullable=False),sa.Column("source_url",sa.String(1000),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("ended_at",sa.DateTime(timezone=True)))
 tenant("live_updates",sa.Column("stream_id",sa.String(36),sa.ForeignKey("live_streams.id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.BigInteger(),nullable=False),sa.Column("update_type",sa.String(30),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("asset_id",sa.String(36),sa.ForeignKey("media_assets.id",ondelete="SET NULL")),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("stream_id","sequence",name="uq_live_update_sequence"),))
 tenant("collaborative_documents",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("resource_type",sa.String(20),nullable=False),sa.Column("resource_id",sa.String(36),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("snapshot",sa.JSON(),nullable=False),sa.Column("snapshot_hash",sa.String(64),nullable=False),sa.Column("updated_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","resource_type","resource_id",name="uq_collab_resource"),))
 tenant("collaborative_changes",sa.Column("document_id",sa.String(36),sa.ForeignKey("collaborative_documents.id",ondelete="CASCADE"),nullable=False),sa.Column("base_version",sa.Integer(),nullable=False),sa.Column("result_version",sa.Integer()),sa.Column("client_id",sa.String(80),nullable=False),sa.Column("client_sequence",sa.BigInteger(),nullable=False),sa.Column("operations",sa.JSON(),nullable=False),sa.Column("changed_paths",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("conflict",sa.JSON(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("document_id","client_id","client_sequence",name="uq_collab_client_sequence"),))
 tenant("collaboration_comments",sa.Column("document_id",sa.String(36),sa.ForeignKey("collaborative_documents.id",ondelete="CASCADE"),nullable=False),sa.Column("parent_id",sa.String(36),sa.ForeignKey("collaboration_comments.id",ondelete="CASCADE")),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("anchor",sa.JSON(),nullable=False),sa.Column("mention_user_ids",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 tenant("collaboration_tickets",sa.Column("document_id",sa.String(36),sa.ForeignKey("collaborative_documents.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("ticket_hash",sa.String(64),nullable=False,unique=True),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("consumed_at",sa.DateTime(timezone=True)))
 tenant("collaboration_audits",sa.Column("document_id",sa.String(36),sa.ForeignKey("collaborative_documents.id",ondelete="SET NULL")),sa.Column("actor_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(80),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 if op.get_bind().dialect.name=="postgresql":
  for table in ("media_assets","media_processing_runs","media_evidence","media_citations","live_streams","live_updates","collaborative_documents","collaborative_changes","collaboration_comments","collaboration_tickets","collaboration_audits"):
   op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY");op.execute(f"CREATE POLICY {table}_tenant_policy ON {table} USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))")
def downgrade():
 for table in ("collaboration_audits","collaboration_tickets","collaboration_comments","collaborative_changes","collaborative_documents","live_updates","live_streams","media_citations","media_evidence","media_processing_runs","media_assets"):op.drop_table(table)
