"""Add normalized entities, relation evidence and propagation graphs."""
from alembic import op
import sqlalchemy as sa
revision="20260728_0011";down_revision="20260728_0010";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("entities",sa.Column("id",sa.String(36),primary_key=True),sa.Column("name",sa.String(300),nullable=False),sa.Column("normalized_name",sa.String(300),nullable=False),sa.Column("entity_type",sa.String(30),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("entity_type","normalized_name",name="uq_entity_type_name"))
 op.create_table("entity_aliases",sa.Column("id",sa.String(36),primary_key=True),sa.Column("entity_id",sa.String(36),sa.ForeignKey("entities.id",ondelete="CASCADE"),nullable=False),sa.Column("alias",sa.String(300),nullable=False),sa.Column("normalized_alias",sa.String(300),nullable=False),sa.Column("language",sa.String(16),nullable=False),sa.UniqueConstraint("entity_id","normalized_alias",name="uq_entity_alias"))
 op.create_table("event_entity_links",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("entity_id",sa.String(36),sa.ForeignKey("entities.id",ondelete="CASCADE"),nullable=False),sa.Column("role",sa.String(40),nullable=False),sa.Column("mention_count",sa.Integer(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("evidence_content_ids",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("event_id","entity_id","role",name="uq_event_entity_link"))
 op.create_table("entity_relations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("from_entity_id",sa.String(36),sa.ForeignKey("entities.id",ondelete="CASCADE"),nullable=False),sa.Column("to_entity_id",sa.String(36),sa.ForeignKey("entities.id",ondelete="CASCADE"),nullable=False),sa.Column("relation_type",sa.String(50),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("evidence_content_ids",sa.JSON(),nullable=False),sa.Column("created_by",sa.String(20),nullable=False),sa.Column("is_verified",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("event_id","from_entity_id","to_entity_id","relation_type",name="uq_entity_relation"))
 op.create_table("propagation_nodes",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("content_item_id",sa.String(36),sa.ForeignKey("content_items.id",ondelete="CASCADE"),nullable=False),sa.Column("platform",sa.String(80),nullable=False),sa.Column("node_type",sa.String(30),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True)),sa.Column("influence_score",sa.Float(),nullable=False),sa.Column("is_verified",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("event_id","content_item_id",name="uq_propagation_event_content"))
 op.create_table("propagation_edges",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("from_node_id",sa.String(36),sa.ForeignKey("propagation_nodes.id",ondelete="CASCADE"),nullable=False),sa.Column("to_node_id",sa.String(36),sa.ForeignKey("propagation_nodes.id",ondelete="CASCADE"),nullable=False),sa.Column("relation_type",sa.String(30),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("evidence_content_id",sa.String(36),sa.ForeignKey("content_items.id",ondelete="RESTRICT"),nullable=False),sa.Column("evidence_quote",sa.Text(),nullable=False),sa.Column("created_by",sa.String(20),nullable=False),sa.Column("is_verified",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("from_node_id","to_node_id","relation_type",name="uq_propagation_edge"))
 op.create_table("graph_quality_snapshots",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("entity_precision",sa.Float(),nullable=False),sa.Column("evidence_coverage",sa.Float(),nullable=False),sa.Column("verified_ratio",sa.Float(),nullable=False),sa.Column("unresolved_count",sa.Integer(),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 for table,cols in {"entities":["normalized_name","entity_type"],"entity_aliases":["entity_id","normalized_alias"],"event_entity_links":["event_id","entity_id"],"entity_relations":["event_id","from_entity_id","to_entity_id"],"propagation_nodes":["event_id","content_item_id","platform","occurred_at"],"propagation_edges":["event_id","from_node_id","to_node_id","evidence_content_id"],"graph_quality_snapshots":["event_id"]}.items():
  for col in cols:op.create_index(f"ix_{table}_{col}",table,[col])
def downgrade():
 for table in ("graph_quality_snapshots","propagation_edges","propagation_nodes","entity_relations","event_entity_links","entity_aliases","entities"):op.drop_table(table)
