"""Add Agent conversations, messages, citations and feedback."""
from alembic import op
import sqlalchemy as sa
revision="20260728_0007";down_revision="20260728_0006";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("conversations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="SET NULL")),sa.Column("context_config",sa.JSON(),nullable=False),sa.Column("model_name",sa.String(120),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)))
 op.create_index("ix_conversations_user_id","conversations",["user_id"]);op.create_index("ix_conversations_event_id","conversations",["event_id"])
 op.create_table("agent_messages",sa.Column("id",sa.String(36),primary_key=True),sa.Column("conversation_id",sa.String(36),sa.ForeignKey("conversations.id",ondelete="CASCADE"),nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("tool_name",sa.String(60),nullable=False),sa.Column("tool_payload",sa.JSON(),nullable=False),sa.Column("model_name",sa.String(120),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_agent_messages_conversation_id","agent_messages",["conversation_id"]);op.create_index("ix_agent_messages_created_at","agent_messages",["created_at"])
 op.create_table("message_citations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("message_id",sa.String(36),sa.ForeignKey("agent_messages.id",ondelete="CASCADE"),nullable=False),sa.Column("content_item_id",sa.String(36),sa.ForeignKey("content_items.id",ondelete="RESTRICT"),nullable=False),sa.Column("quote",sa.Text(),nullable=False),sa.Column("locator",sa.JSON(),nullable=False),sa.Column("claim_index",sa.Integer(),nullable=False));op.create_index("ix_message_citations_message_id","message_citations",["message_id"]);op.create_index("ix_message_citations_content_item_id","message_citations",["content_item_id"])
 op.create_table("message_feedback",sa.Column("id",sa.String(36),primary_key=True),sa.Column("message_id",sa.String(36),sa.ForeignKey("agent_messages.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("rating",sa.String(10),nullable=False),sa.Column("reason",sa.String(500),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("message_id","user_id",name="uq_message_feedback"));op.create_index("ix_message_feedback_message_id","message_feedback",["message_id"]);op.create_index("ix_message_feedback_user_id","message_feedback",["user_id"])
def downgrade():
 for x in ("message_feedback","message_citations","agent_messages","conversations"):op.drop_table(x)
