"""Add reports, immutable versions and exports."""
from alembic import op
import sqlalchemy as sa
revision="20260728_0008";down_revision="20260728_0007";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("reports",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("report_type",sa.String(30),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("source_config",sa.JSON(),nullable=False),sa.Column("current_version_id",sa.String(36)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)));op.create_index("ix_reports_user_id","reports",["user_id"])
 op.create_table("report_versions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("report_id",sa.String(36),sa.ForeignKey("reports.id",ondelete="CASCADE"),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("content_markdown",sa.Text(),nullable=False),sa.Column("structured_content",sa.JSON(),nullable=False),sa.Column("citations",sa.JSON(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("report_id","version_number",name="uq_report_version"));op.create_index("ix_report_versions_report_id","report_versions",["report_id"])
 op.create_table("report_exports",sa.Column("id",sa.String(36),primary_key=True),sa.Column("report_id",sa.String(36),sa.ForeignKey("reports.id",ondelete="CASCADE"),nullable=False),sa.Column("version_id",sa.String(36),sa.ForeignKey("report_versions.id",ondelete="CASCADE"),nullable=False),sa.Column("format",sa.String(20),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("storage_key",sa.String(1000),nullable=False),sa.Column("file_size",sa.BigInteger(),nullable=False),sa.Column("error_message",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_report_exports_report_id","report_exports",["report_id"])
def downgrade():
 for x in ("report_exports","report_versions","reports"):op.drop_table(x)
