"""Stage 20 decision productization and commercialization."""
from alembic import op
import sqlalchemy as sa
revision="20260801_0021";down_revision="20260731_0020";branch_labels=None;depends_on=None
def org_table(name,*columns,constraints=()):
 op.create_table(name,sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),*columns,*constraints);op.create_index(f"ix_{name}_organization_id",name,["organization_id"])
def upgrade():
 org_table("template_packages",sa.Column("key",sa.String(80),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("visibility",sa.String(20),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("current_version",sa.Integer(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","key",name="uq_template_package_key"),))
 org_table("template_package_versions",sa.Column("package_id",sa.String(36),sa.ForeignKey("template_packages.id",ondelete="CASCADE"),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("definition",sa.JSON(),nullable=False),sa.Column("change_note",sa.String(500),nullable=False),sa.Column("rollback_of_version",sa.Integer()),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("package_id","version",name="uq_template_package_version"),))
 org_table("approval_flows",sa.Column("name",sa.String(160),nullable=False),sa.Column("trigger",sa.String(60),nullable=False),sa.Column("graph",sa.JSON(),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 org_table("metric_collectors",sa.Column("metric_id",sa.String(36),sa.ForeignKey("impact_metric_definitions.id",ondelete="CASCADE"),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("config",sa.JSON(),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("last_collected_at",sa.DateTime(timezone=True)),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False))
 org_table("attribution_audits",sa.Column("measurement_id",sa.String(36),sa.ForeignKey("impact_measurements.id",ondelete="CASCADE"),nullable=False),sa.Column("method",sa.String(40),nullable=False),sa.Column("assumptions",sa.JSON(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("conclusion",sa.String(30),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 org_table("sla_policies",sa.Column("name",sa.String(160),nullable=False),sa.Column("target_type",sa.String(50),nullable=False),sa.Column("target_minutes",sa.Integer(),nullable=False),sa.Column("warning_minutes",sa.Integer(),nullable=False),sa.Column("escalation_steps",sa.JSON(),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("usage_entitlements",sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE"),primary_key=True),sa.Column("plan_key",sa.String(40),nullable=False),sa.Column("limits",sa.JSON(),nullable=False),sa.Column("feature_flags",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 org_table("product_usage",sa.Column("period",sa.String(7),nullable=False),sa.Column("feature",sa.String(80),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.Column("cost_cents",sa.Integer(),nullable=False),sa.Column("dimensions",sa.JSON(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","period","feature",name="uq_product_usage_feature"),))
 org_table("connector_executions",sa.Column("installation_id",sa.String(36),sa.ForeignKey("connector_installations.id",ondelete="CASCADE"),nullable=False),sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="SET NULL")),sa.Column("provider",sa.String(20),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("response_code",sa.Integer()),sa.Column("external_reference",sa.String(300),nullable=False),sa.Column("error",sa.String(500),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)),constraints=(sa.UniqueConstraint("organization_id","idempotency_key",name="uq_connector_execution_idempotency"),))
def downgrade():
 for name in ("connector_executions","product_usage","usage_entitlements","sla_policies","attribution_audits","metric_collectors","approval_flows","template_package_versions","template_packages"):op.drop_table(name)
