"""Stage 21 autonomous enterprise and compliance scale."""
from alembic import op
import sqlalchemy as sa
revision="20260801_0022";down_revision="20260801_0021";branch_labels=None;depends_on=None
U=lambda:sa.String(36)
def base(name,*cols,constraints=()):
 op.create_table(name,sa.Column("id",U(),primary_key=True),sa.Column("organization_id",U(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),*cols,*constraints);op.create_index(f"ix_{name}_organization_id",name,["organization_id"])
def user(name="created_by"):return sa.Column(name,U(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False)
def upgrade():
 base("connector_credential_leases",sa.Column("installation_id",U(),sa.ForeignKey("connector_installations.id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(30),nullable=False),sa.Column("secret_reference",sa.String(500),nullable=False),sa.Column("secret_fingerprint",sa.String(64),nullable=False),sa.Column("region",sa.String(24),nullable=False),sa.Column("egress_policy",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("rotated_from_id",U(),sa.ForeignKey("connector_credential_leases.id",ondelete="SET NULL")),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("last_health_at",sa.DateTime(timezone=True)),user(),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 base("approval_runs",sa.Column("flow_id",U(),sa.ForeignKey("approval_flows.id",ondelete="RESTRICT"),nullable=False),sa.Column("subject_type",sa.String(50),nullable=False),sa.Column("subject_id",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("context",sa.JSON(),nullable=False),sa.Column("signature_chain",sa.JSON(),nullable=False),sa.Column("compensation_log",sa.JSON(),nullable=False),user("started_by"),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)),constraints=(sa.UniqueConstraint("organization_id","idempotency_key",name="uq_approval_run_idempotency"),))
 base("approval_node_runs",sa.Column("run_id",U(),sa.ForeignKey("approval_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("node_id",sa.String(80),nullable=False),sa.Column("node_type",sa.String(30),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("assignee_id",U(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("delegated_to_id",U(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("decision",sa.String(20),nullable=False),sa.Column("signature",sa.String(64),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),constraints=(sa.UniqueConstraint("run_id","node_id",name="uq_approval_node_run"),))
 base("causal_experiments",sa.Column("name",sa.String(180),nullable=False),sa.Column("metric_key",sa.String(100),nullable=False),sa.Column("method",sa.String(30),nullable=False),sa.Column("treatment",sa.JSON(),nullable=False),sa.Column("control",sa.JSON(),nullable=False),sa.Column("confounders",sa.JSON(),nullable=False),sa.Column("window",sa.JSON(),nullable=False),sa.Column("minimum_sample",sa.Integer(),nullable=False),sa.Column("power",sa.Float(),nullable=False),sa.Column("effect",sa.Float()),sa.Column("confidence_interval",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),user(),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 base("financial_ledger",sa.Column("entry_type",sa.String(30),nullable=False),sa.Column("department",sa.String(100),nullable=False),sa.Column("amount_cents",sa.Integer(),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("external_reference",sa.String(160),nullable=False),sa.Column("provider",sa.String(30),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","external_reference",name="uq_financial_external_ref"),))
 base("billing_documents",sa.Column("document_type",sa.String(20),nullable=False),sa.Column("period",sa.String(7),nullable=False),sa.Column("amount_cents",sa.Integer(),nullable=False),sa.Column("tax_cents",sa.Integer(),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("provider_reference",sa.String(160),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("issued_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 base("privacy_budgets",sa.Column("dataset_key",sa.String(100),nullable=False),sa.Column("period",sa.String(7),nullable=False),sa.Column("epsilon_limit",sa.Float(),nullable=False),sa.Column("epsilon_used",sa.Float(),nullable=False),sa.Column("delta",sa.Float(),nullable=False),sa.Column("minimum_cohort",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),constraints=(sa.UniqueConstraint("organization_id","dataset_key","period",name="uq_privacy_budget"),))
 base("privacy_query_audits",sa.Column("budget_id",U(),sa.ForeignKey("privacy_budgets.id",ondelete="CASCADE"),nullable=False),sa.Column("query_fingerprint",sa.String(64),nullable=False),sa.Column("epsilon_cost",sa.Float(),nullable=False),sa.Column("cohort_size",sa.Integer(),nullable=False),sa.Column("attack_risk",sa.Float(),nullable=False),sa.Column("status",sa.String(20),nullable=False),user(),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 base("policy_bundles",sa.Column("key",sa.String(80),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("current_version",sa.Integer(),nullable=False),sa.Column("active_version",sa.Integer()),sa.Column("canary_percent",sa.Integer(),nullable=False),user(),constraints=(sa.UniqueConstraint("organization_id","key",name="uq_policy_bundle_key"),))
 base("policy_versions",sa.Column("bundle_id",U(),sa.ForeignKey("policy_bundles.id",ondelete="CASCADE"),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("rules",sa.JSON(),nullable=False),sa.Column("test_cases",sa.JSON(),nullable=False),sa.Column("simulation",sa.JSON(),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("status",sa.String(20),nullable=False),user(),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("bundle_id","version",name="uq_policy_version"),))
 base("recovery_drills",sa.Column("region",sa.String(24),nullable=False),sa.Column("drill_type",sa.String(40),nullable=False),sa.Column("rpo_target_minutes",sa.Integer(),nullable=False),sa.Column("rto_target_minutes",sa.Integer(),nullable=False),sa.Column("actual_rpo_minutes",sa.Integer()),sa.Column("actual_rto_minutes",sa.Integer()),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("isolation_verified",sa.Boolean(),nullable=False),sa.Column("status",sa.String(20),nullable=False),user(),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 base("compliance_controls",sa.Column("framework",sa.String(30),nullable=False),sa.Column("control_key",sa.String(60),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("owner_id",U(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("exceptions",sa.JSON(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","framework","control_key",name="uq_compliance_control"),))
 base("compliance_evidence",sa.Column("control_id",U(),sa.ForeignKey("compliance_controls.id",ondelete="CASCADE"),nullable=False),sa.Column("evidence_type",sa.String(40),nullable=False),sa.Column("locator",sa.String(500),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("collected_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("metadata",sa.JSON(),nullable=False))
 base("safety_evaluations",sa.Column("target_type",sa.String(40),nullable=False),sa.Column("target_id",sa.String(64),nullable=False),sa.Column("scenario",sa.String(100),nullable=False),sa.Column("results",sa.JSON(),nullable=False),sa.Column("permission_drift",sa.Boolean(),nullable=False),sa.Column("rollback_verified",sa.Boolean(),nullable=False),sa.Column("score",sa.Float(),nullable=False),sa.Column("gate_status",sa.String(20),nullable=False),user(),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
 for name in ("safety_evaluations","compliance_evidence","compliance_controls","recovery_drills","policy_versions","policy_bundles","privacy_query_audits","privacy_budgets","billing_documents","financial_ledger","causal_experiments","approval_node_runs","approval_runs","connector_credential_leases"):op.drop_table(name)
