"""Add alert lifecycle, replay, controlled BI history and model usage."""
from alembic import op
import sqlalchemy as sa
revision="20260729_0012";down_revision="20260728_0011";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("alert_rules",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("rule_type",sa.String(30),nullable=False),sa.Column("config",sa.JSON(),nullable=False),sa.Column("combinator",sa.String(10),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("assignee_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("alert_incidents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("rule_id",sa.String(36),sa.ForeignKey("alert_rules.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="SET NULL")),sa.Column("status",sa.String(20),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("assignee_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("is_false_positive",sa.Boolean(),nullable=False),sa.Column("triggered_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("rule_id","event_id","fingerprint",name="uq_alert_incident_fingerprint"))
 op.create_table("alert_actions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("incident_id",sa.String(36),sa.ForeignKey("alert_incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("action",sa.String(30),nullable=False),sa.Column("note",sa.Text(),nullable=False),sa.Column("before_status",sa.String(20),nullable=False),sa.Column("after_status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("alert_replay_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("rule_id",sa.String(36),sa.ForeignKey("alert_rules.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("from_at",sa.DateTime(timezone=True),nullable=False),sa.Column("to_at",sa.DateTime(timezone=True),nullable=False),sa.Column("matched_count",sa.Integer(),nullable=False),sa.Column("sample_results",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("bi_query_history",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("question",sa.String(1000),nullable=False),sa.Column("query_plan",sa.JSON(),nullable=False),sa.Column("result",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("model_usage",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("feature",sa.String(40),nullable=False),sa.Column("model_name",sa.String(120),nullable=False),sa.Column("prompt_tokens",sa.Integer(),nullable=False),sa.Column("completion_tokens",sa.Integer(),nullable=False),sa.Column("cost",sa.Float(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 for table,cols in {"alert_rules":["user_id","rule_type","assignee_id"],"alert_incidents":["rule_id","user_id","event_id","status","assignee_id","triggered_at"],"alert_actions":["incident_id","user_id","created_at"],"alert_replay_runs":["rule_id","user_id"],"bi_query_history":["user_id","created_at"],"model_usage":["user_id","feature","model_name","created_at"]}.items():
  for col in cols:op.create_index(f"ix_{table}_{col}",table,[col])
def downgrade():
 for table in ("model_usage","bi_query_history","alert_replay_runs","alert_actions","alert_incidents","alert_rules"):op.drop_table(table)
