"""Add durable agent orchestration, memory and evaluations.

Revision ID: 20260730_0017
Revises: 20260730_0016
"""
from alembic import op
import sqlalchemy as sa

revision="20260730_0017"; down_revision="20260730_0016"; branch_labels=None; depends_on=None

def tenant(name,*cols,constraints=()):
    op.create_table(name,sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),*cols,*constraints)
    op.create_index(f"ix_{name}_organization_id",name,["organization_id"])

def upgrade():
    tenant("agent_tools",sa.Column("key",sa.String(80),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("description",sa.String(500),nullable=False),sa.Column("input_schema",sa.JSON(),nullable=False),sa.Column("risk_level",sa.String(16),nullable=False),sa.Column("connector_key",sa.String(40),sa.ForeignKey("connector_definitions.key",ondelete="RESTRICT")),sa.Column("action",sa.String(80),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","key",name="uq_agent_tool_key"),))
    tenant("agent_tool_policies",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("tool_id",sa.String(36),sa.ForeignKey("agent_tools.id",ondelete="CASCADE"),nullable=False),sa.Column("effect",sa.String(12),nullable=False),sa.Column("require_approval",sa.Boolean(),nullable=False),sa.Column("max_calls_per_run",sa.Integer(),nullable=False),sa.Column("constraints",sa.JSON(),nullable=False),constraints=(sa.UniqueConstraint("workspace_id","tool_id",name="uq_agent_tool_policy"),))
    tenant("agent_prompts",sa.Column("key",sa.String(80),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("system_prompt",sa.Text(),nullable=False),sa.Column("input_variables",sa.JSON(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","key","version",name="uq_agent_prompt_version"),))
    tenant("agent_model_routes",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("task_type",sa.String(60),nullable=False),sa.Column("primary_model",sa.String(120),nullable=False),sa.Column("fallback_models",sa.JSON(),nullable=False),sa.Column("max_cost_cents",sa.Integer(),nullable=False),sa.Column("max_tokens",sa.Integer(),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),constraints=(sa.UniqueConstraint("workspace_id","task_type",name="uq_agent_model_route"),))
    tenant("agent_workflows",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("name",sa.String(160),nullable=False),sa.Column("description",sa.String(1000),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("active_version_id",sa.String(36)),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("agent_workflow_versions",sa.Column("workflow_id",sa.String(36),sa.ForeignKey("agent_workflows.id",ondelete="CASCADE"),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("graph",sa.JSON(),nullable=False),sa.Column("change_note",sa.String(500),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("workflow_id","version",name="uq_agent_workflow_version"),))
    tenant("agent_workflow_runs",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("workflow_id",sa.String(36),sa.ForeignKey("agent_workflows.id",ondelete="CASCADE"),nullable=False),sa.Column("version_id",sa.String(36),sa.ForeignKey("agent_workflow_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("current_node_id",sa.String(80)),sa.Column("input",sa.JSON(),nullable=False),sa.Column("output",sa.JSON(),nullable=False),sa.Column("budget_cents",sa.Integer(),nullable=False),sa.Column("spent_cents",sa.Integer(),nullable=False),sa.Column("idempotency_key",sa.String(100),nullable=False),sa.Column("lease_owner",sa.String(100)),sa.Column("lease_until",sa.DateTime(timezone=True)),sa.Column("parent_run_id",sa.String(36),sa.ForeignKey("agent_workflow_runs.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),constraints=(sa.UniqueConstraint("organization_id","idempotency_key",name="uq_agent_run_idempotency"),))
    tenant("agent_workflow_step_runs",sa.Column("run_id",sa.String(36),sa.ForeignKey("agent_workflow_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("node_id",sa.String(80),nullable=False),sa.Column("node_type",sa.String(24),nullable=False),sa.Column("attempt",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("input",sa.JSON(),nullable=False),sa.Column("output",sa.JSON(),nullable=False),sa.Column("error",sa.String(2000),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),constraints=(sa.UniqueConstraint("run_id","node_id","attempt",name="uq_agent_step_attempt"),))
    tenant("agent_workflow_approvals",sa.Column("run_id",sa.String(36),sa.ForeignKey("agent_workflow_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("step_run_id",sa.String(36),sa.ForeignKey("agent_workflow_step_runs.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("risk_summary",sa.String(1000),nullable=False),sa.Column("requested_action",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("requested_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("decided_by",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("decision_note",sa.String(1000),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("decided_at",sa.DateTime(timezone=True)))
    tenant("agent_memories",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("run_id",sa.String(36),sa.ForeignKey("agent_workflow_runs.id",ondelete="CASCADE")),sa.Column("namespace",sa.String(80),nullable=False),sa.Column("key",sa.String(120),nullable=False),sa.Column("value",sa.JSON(),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("organization_id","workspace_id","user_id","namespace","key",name="uq_agent_memory"),))
    tenant("agent_evaluation_datasets",sa.Column("name",sa.String(160),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("cases",sa.JSON(),nullable=False),sa.Column("thresholds",sa.JSON(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("agent_evaluation_runs",sa.Column("dataset_id",sa.String(36),sa.ForeignKey("agent_evaluation_datasets.id",ondelete="CASCADE"),nullable=False),sa.Column("workflow_version_id",sa.String(36),sa.ForeignKey("agent_workflow_versions.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("score",sa.Float(),nullable=False),sa.Column("passed",sa.Boolean(),nullable=False),sa.Column("results",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)))
    op.create_table("agent_workflow_templates",sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE")),sa.Column("key",sa.String(80),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("category",sa.String(40),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("graph",sa.JSON(),nullable=False),sa.Column("published",sa.Boolean(),nullable=False),sa.UniqueConstraint("organization_id","key","version",name="uq_agent_template_version"))
    tenant("agent_orchestration_audits",sa.Column("run_id",sa.String(36),sa.ForeignKey("agent_workflow_runs.id",ondelete="SET NULL")),sa.Column("actor_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(80),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    if op.get_bind().dialect.name=="postgresql":
        for table in ("agent_tools","agent_tool_policies","agent_prompts","agent_model_routes","agent_workflows","agent_workflow_versions","agent_workflow_runs","agent_workflow_step_runs","agent_workflow_approvals","agent_memories","agent_evaluation_datasets","agent_evaluation_runs","agent_orchestration_audits"):
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY");op.execute(f"CREATE POLICY {table}_tenant_policy ON {table} USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))")
        op.execute("ALTER TABLE agent_workflow_templates ENABLE ROW LEVEL SECURITY");op.execute("CREATE POLICY agent_workflow_templates_tenant_policy ON agent_workflow_templates USING (organization_id IS NULL OR organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))")

def downgrade():
    for table in ("agent_orchestration_audits","agent_workflow_templates","agent_evaluation_runs","agent_evaluation_datasets","agent_memories","agent_workflow_approvals","agent_workflow_step_runs","agent_workflow_runs","agent_workflow_versions","agent_workflows","agent_model_routes","agent_prompts","agent_tool_policies","agent_tools"):op.drop_table(table)
