"""Add multilingual intelligence and decision support.

Revision ID: 20260731_0019
Revises: 20260730_0018
"""
from alembic import op
import sqlalchemy as sa
revision="20260731_0019";down_revision="20260730_0018";branch_labels=None;depends_on=None
def tenant(name,*cols,constraints=()):
 op.create_table(name,sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),*cols,*constraints);op.create_index(f"ix_{name}_organization_id",name,["organization_id"])
def upgrade():
 tenant("content_translations",sa.Column("content_item_id",sa.String(36),sa.ForeignKey("content_items.id",ondelete="CASCADE"),nullable=False),sa.Column("source_language",sa.String(16),nullable=False),sa.Column("target_language",sa.String(16),nullable=False),sa.Column("translated_title",sa.Text(),nullable=False),sa.Column("translated_body",sa.Text(),nullable=False),sa.Column("model_name",sa.String(120),nullable=False),sa.Column("quality_score",sa.Float(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),constraints=(sa.UniqueConstraint("content_item_id","target_language",name="uq_translation_content_language"),))
 tenant("global_narratives",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(400),nullable=False),sa.Column("normalized_key",sa.String(400),nullable=False),sa.Column("languages",sa.JSON(),nullable=False),sa.Column("regions",sa.JSON(),nullable=False),sa.Column("content_item_ids",sa.JSON(),nullable=False),sa.Column("entity_ids",sa.JSON(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 tenant("narrative_signals",sa.Column("narrative_id",sa.String(36),sa.ForeignKey("global_narratives.id",ondelete="CASCADE"),nullable=False),sa.Column("signal_type",sa.String(50),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("evidence_content_ids",sa.JSON(),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 tenant("scenarios",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(300),nullable=False),sa.Column("assumptions",sa.JSON(),nullable=False),sa.Column("impact_chain",sa.JSON(),nullable=False),sa.Column("risk_score",sa.Float(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("evidence_content_ids",sa.JSON(),nullable=False),sa.Column("evidence_gaps",sa.JSON(),nullable=False),sa.Column("model_name",sa.String(120),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 tenant("decision_rooms",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(300),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("frozen_at",sa.DateTime(timezone=True)),sa.Column("frozen_by",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 tenant("decision_options",sa.Column("room_id",sa.String(36),sa.ForeignKey("decision_rooms.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("constraints",sa.JSON(),nullable=False),sa.Column("benefits",sa.JSON(),nullable=False),sa.Column("side_effects",sa.JSON(),nullable=False),sa.Column("counterfactuals",sa.JSON(),nullable=False),sa.Column("red_team_questions",sa.JSON(),nullable=False),sa.Column("evidence_content_ids",sa.JSON(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 tenant("decision_audits",sa.Column("room_id",sa.String(36),sa.ForeignKey("decision_rooms.id",ondelete="CASCADE"),nullable=False),sa.Column("actor_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(80),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 if op.get_bind().dialect.name=="postgresql":
  for table in ("content_translations","global_narratives","narrative_signals","scenarios","decision_rooms","decision_options","decision_audits"):
   op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY");op.execute(f"CREATE POLICY {table}_tenant_policy ON {table} USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))")
def downgrade():
 for table in ("decision_audits","decision_options","decision_rooms","scenarios","narrative_signals","global_narratives","content_translations"):op.drop_table(table)
