"""Add response action loop and impact validation records."""
from alembic import op
import sqlalchemy as sa
revision="20260731_0020"; down_revision="20260731_0019"; branch_labels=None; depends_on=None
def tenant(name,*cols,constraints=()):
    op.create_table(name,sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),*cols,*constraints); op.create_index(f"ix_{name}_organization_id",name,["organization_id"])
def upgrade():
    tenant("response_actions",sa.Column("workspace_id",sa.String(36),sa.ForeignKey("enterprise_workspaces.id",ondelete="CASCADE")),sa.Column("event_id",sa.String(36),sa.ForeignKey("events.id",ondelete="SET NULL")),sa.Column("scenario_id",sa.String(36),sa.ForeignKey("scenarios.id",ondelete="SET NULL")),sa.Column("decision_room_id",sa.String(36),sa.ForeignKey("decision_rooms.id",ondelete="SET NULL")),sa.Column("title",sa.String(300),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("owner_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("due_at",sa.DateTime(timezone=True)),sa.Column("sla_minutes",sa.Integer()),sa.Column("budget_cents",sa.Integer(),nullable=False),sa.Column("spent_cents",sa.Integer(),nullable=False),sa.Column("escalation_policy",sa.JSON(),nullable=False),sa.Column("stop_conditions",sa.JSON(),nullable=False),sa.Column("dependency_ids",sa.JSON(),nullable=False),sa.Column("evidence_content_ids",sa.JSON(),nullable=False),sa.Column("risk_level",sa.String(20),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("action_steps",sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="CASCADE"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("channel",sa.String(40),nullable=False),sa.Column("tool_key",sa.String(120)),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("requires_approval",sa.Boolean(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("error_message",sa.Text(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)))
    tenant("action_runs",sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="CASCADE"),nullable=False),sa.Column("idempotency_key",sa.String(200),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("attempt",sa.Integer(),nullable=False),sa.Column("output",sa.JSON(),nullable=False),sa.Column("error_message",sa.Text(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)),constraints=(sa.UniqueConstraint("action_id","idempotency_key",name="uq_action_run_idempotency"),))
    tenant("action_receipts",sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="CASCADE"),nullable=False),sa.Column("run_id",sa.String(36),sa.ForeignKey("action_runs.id",ondelete="SET NULL")),sa.Column("step_id",sa.String(36),sa.ForeignKey("action_steps.id",ondelete="SET NULL")),sa.Column("channel",sa.String(40),nullable=False),sa.Column("external_reference",sa.String(300),nullable=False),sa.Column("response_code",sa.Integer()),sa.Column("receipt_payload",sa.JSON(),nullable=False),sa.Column("evidence_content_ids",sa.JSON(),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False))
    tenant("impact_metric_definitions",sa.Column("key",sa.String(100),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("unit",sa.String(40),nullable=False),sa.Column("direction",sa.String(20),nullable=False),sa.Column("definition",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("impact_measurements",sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="CASCADE"),nullable=False),sa.Column("metric_id",sa.String(36),sa.ForeignKey("impact_metric_definitions.id",ondelete="CASCADE"),nullable=False),sa.Column("before_value",sa.Float(),nullable=False),sa.Column("after_value",sa.Float(),nullable=False),sa.Column("attribution_confidence",sa.Float(),nullable=False),sa.Column("attribution_boundary",sa.Text(),nullable=False),sa.Column("source_content_ids",sa.JSON(),nullable=False),sa.Column("notes",sa.Text(),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False))
    tenant("action_reviews",sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="CASCADE"),nullable=False),sa.Column("reviewer_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("outcome",sa.String(30),nullable=False),sa.Column("failure_mode",sa.String(120),nullable=False),sa.Column("lessons",sa.Text(),nullable=False),sa.Column("stop_condition_met",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("anonymous_benchmarks",sa.Column("metric_key",sa.String(100),nullable=False),sa.Column("cohort",sa.String(100),nullable=False),sa.Column("sample_size",sa.Integer(),nullable=False),sa.Column("aggregate_value",sa.Float(),nullable=False),sa.Column("k_anonymity",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("action_drills",sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="SET NULL")),sa.Column("drill_type",sa.String(50),nullable=False),sa.Column("input_snapshot",sa.JSON(),nullable=False),sa.Column("expected_result",sa.JSON(),nullable=False),sa.Column("actual_result",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("action_audits",sa.Column("action_id",sa.String(36),sa.ForeignKey("response_actions.id",ondelete="SET NULL")),sa.Column("actor_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(80),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    tenant("action_templates",sa.Column("name",sa.String(200),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("definition",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for t in ("action_templates","action_audits","action_drills","anonymous_benchmarks","action_reviews","impact_measurements","impact_metric_definitions","action_receipts","action_runs","action_steps","response_actions"): op.drop_table(t)
