<template>
  <main class="page">
    <header><div><p class="eyebrow">STAGE 24 OPERATING SYSTEM</p><h1>自适应全球情报操作系统</h1><p>协议演进、自治政策、主权路由与持续保证的统一生产控制面。</p></div><el-button :icon="Refresh" circle title="刷新" :loading="loading" @click="load" /></header>
    <section class="metrics"><div v-for="item in metrics" :key="item.key"><span>{{ item.label }}</span><strong>{{ overview[item.key] ?? 0 }}</strong></div></section>
    <el-tabs v-model="tab">
      <el-tab-pane label="自治控制" name="control"><section class="grid"><article v-for="item in controls" :key="item.title"><el-icon><component :is="item.icon" /></el-icon><h2>{{ item.title }}</h2><p>{{ item.text }}</p><el-tag :type="item.type" effect="plain">{{ item.state }}</el-tag></article></section></el-tab-pane>
      <el-tab-pane label="协议金丝雀" name="rollout"><section class="form-band"><h2>创建协议升级</h2><el-form label-position="top"><div class="three"><el-form-item label="协议"><el-input v-model="rollout.protocol_key" /></el-form-item><el-form-item label="当前版本"><el-input v-model="rollout.from_version" /></el-form-item><el-form-item label="目标版本"><el-input v-model="rollout.to_version" /></el-form-item></div><el-slider v-model="rollout.canary_percent" :min="1" :max="100" show-input /><el-button type="primary" :icon="Promotion" @click="startRollout">启动金丝雀</el-button></el-form></section></el-tab-pane>
      <el-tab-pane label="全球韧性" name="resilience"><section class="grid"><article><el-icon><DataAnalysis /></el-icon><h2>数字孪生</h2><p>重放区域断网、供应链退出、制裁、汇率冲击和信息污染。</p></article><article><el-icon><Warning /></el-icon><h2>市场熔断</h2><p>流动性、抵押品、异常交易与压力损失统一门禁。</p></article><article><el-icon><Compass /></el-icon><h2>主权路由</h2><p>仅在数据驻留区域选择具备许可的推理模型。</p></article></section></el-tab-pane>
    </el-tabs>
  </main>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { CircleCheck, Compass, DataAnalysis, DocumentChecked, Promotion, Refresh, Warning } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { adaptiveOsApi } from '@/api/adaptiveOs'
const loading=ref(false),tab=ref('control');const overview=reactive<Record<string,number>>({});const rollout=reactive({protocol_key:'federation',from_version:'2.0',to_version:'3.0',compatibility_matrix:{'2.0->3.0':true},canary_percent:5,health:{error_rate:0,max_error_rate:.02,latency_ms:50,max_latency_ms:200}})
const metrics=computed(()=>[{key:'rollouts',label:'协议升级'},{key:'policies',label:'自治政策'},{key:'transparency_entries',label:'透明日志'},{key:'simulations',label:'孪生演练'},{key:'open_circuits',label:'熔断市场'},{key:'blocked_assurance',label:'保证阻断'},{key:'proposals',label:'治理提案'}]);const controls=[{title:'政策形式验证',text:'形式验证、沙箱差异与双人审批缺一不可。',state:'强制门禁',type:'danger',icon:DocumentChecked},{title:'密码学透明日志',text:'模型、政策与责任事件支持包含证明和外部见证。',state:'可验证',type:'success',icon:CircleCheck},{title:'持续保证',text:'证据新鲜度和控制通过率实时计算置信度。',state:'持续监测',type:'warning',icon:DataAnalysis}]
async function load(){loading.value=true;try{Object.assign(overview,await adaptiveOsApi.overview())}finally{loading.value=false}}async function startRollout(){try{const result=await adaptiveOsApi.rollout(rollout);ElMessage[result.status==='rolled_back'?'warning':'success'](result.status==='rolled_back'?'金丝雀已自动回滚':'金丝雀已启动');await load()}catch{ElMessage.error('协议升级创建失败')}}onMounted(load)
</script>
<style scoped>.page{max-width:1220px;margin:auto;padding:28px 24px 48px}.page header{display:flex;justify-content:space-between;gap:24px;border-bottom:1px solid var(--el-border-color);padding-bottom:20px}.page h1{font-size:30px;margin:4px 0 6px;letter-spacing:0}.page header p{margin:0;color:var(--el-text-color-secondary)}.eyebrow{font-size:12px!important;color:var(--el-color-primary)!important;font-weight:700}.metrics{display:grid;grid-template-columns:repeat(7,1fr);margin-bottom:22px}.metrics>div{padding:18px 14px;border-bottom:1px solid var(--el-border-color);border-right:1px solid var(--el-border-color)}.metrics span{display:block;font-size:12px;color:var(--el-text-color-secondary)}.metrics strong{font-size:25px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;border:1px solid var(--el-border-color);background:var(--el-border-color)}article{background:var(--el-bg-color);padding:24px;min-height:180px}article .el-icon{font-size:25px;color:var(--el-color-primary)}article h2,.form-band h2{font-size:17px}article p{color:var(--el-text-color-secondary);line-height:1.6}.form-band{max-width:800px;padding:12px 0}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}@media(max-width:800px){.metrics{grid-template-columns:repeat(2,1fr)}.grid,.three{grid-template-columns:1fr}.page{padding:18px 14px}.page h1{font-size:25px}}</style>
