<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{stage10Api}from'@/api/stage10';import{operationsApi}from'@/api/operations'
const sources=ref<any[]>([]),tasks=ref<any>({tasks:{},runs:{}}),usage=ref<any>({usage:[],generated_objects:{}}),audits=ref<any[]>([]),analytics=ref<any>({events:{},feedback:{},top_routes:[]}),feedback=ref<any[]>([]),releases=ref<any[]>([]),tab=ref('health');const release=reactive({version:'',environment:'staging',status:'succeeded',commit_sha:'',notes:'',metrics:{}})
async function load(){[sources.value,tasks.value,usage.value,audits.value,analytics.value,feedback.value,releases.value]=await Promise.all([stage10Api.sourceHealth(),stage10Api.taskHealth(),stage10Api.modelUsage(),stage10Api.audits(),operationsApi.analytics(),operationsApi.feedbackQueue(),operationsApi.releases()])}
async function addRelease(){await operationsApi.createRelease(release);ElMessage.success('发布记录已保存');release.version='';release.commit_sha='';release.notes='';releases.value=await operationsApi.releases()}
onMounted(load)
</script>
<template><main><header><small>PLATFORM OPERATIONS</small><h1>运行管理</h1><p>查看运行健康、模型用量、审计记录、用户反馈与版本发布，不回显密钥和私有正文。</p></header><nav><button :class="{active:tab==='health'}" @click="tab='health'">运行健康</button><button :class="{active:tab==='usage'}" @click="tab='usage'">模型用量</button><button :class="{active:tab==='operations'}" @click="tab='operations'">产品运营</button><button :class="{active:tab==='audit'}" @click="tab='audit'">审计日志</button></nav>
<section v-if="tab==='health'"><div class="summary"><article><span>数据源</span><strong>{{sources.length}}</strong></article><article><span>异常来源</span><strong>{{sources.filter(x=>!['healthy','ok'].includes(x.status)).length}}</strong></article><article><span>失败投递</span><strong>{{tasks.failed_deliveries||0}}</strong></article></div><h2>数据源健康</h2><div class="table"><div v-for="x in sources" :key="x.id"><strong>{{x.name}}</strong><span>{{x.type}}</span><i :class="x.status">{{x.status}}</i><small>{{x.last_success_at?new Date(x.last_success_at).toLocaleString():'尚未成功同步'}}</small><em>{{x.last_error?'存在脱敏错误记录':'无错误'}}</em></div></div><h2>任务状态</h2><div class="chips"><span v-for="(v,k) in tasks.tasks" :key="k">{{k}} {{v}}</span><span v-for="(v,k) in tasks.runs" :key="k">运行 {{k}} {{v}}</span></div></section>
<section v-else-if="tab==='usage'"><p class="note">{{usage.note}}</p><div class="table"><div v-for="x in usage.usage" :key="x.model+x.feature"><strong>{{x.model}}</strong><span>{{x.feature}}</span><span>输入 {{x.prompt_tokens}}</span><span>输出 {{x.completion_tokens}}</span><em>¥{{x.cost}}</em></div></div><div v-if="!usage.usage.length" class="empty">尚无精确 Token 用量记录</div><h2>历史生成对象</h2><pre>{{JSON.stringify(usage.generated_objects,null,2)}}</pre></section>
<section v-else-if="tab==='operations'"><div class="summary"><article><span>近 30 天事件</span><strong>{{Object.values(analytics.events).reduce((a:any,b:any)=>a+b,0)}}</strong></article><article><span>反馈数量</span><strong>{{feedback.length}}</strong></article><article><span>平均评分</span><strong>{{analytics.average_rating??'--'}}</strong></article></div><h2>反馈队列</h2><div class="feedback-row" v-for="x in feedback" :key="x.id"><strong>{{x.category}} · {{x.rating}} 分</strong><p>{{x.message}}</p><span>{{x.status}}</span></div><div v-if="!feedback.length" class="empty">暂无用户反馈</div><h2>版本发布记录</h2><form class="release-form" @submit.prevent="addRelease"><input v-model="release.version" required placeholder="版本，例如 1.2.0"/><select v-model="release.environment"><option>staging</option><option>production</option></select><input v-model="release.commit_sha" required minlength="7" placeholder="Commit SHA"/><textarea v-model="release.notes" placeholder="发布说明"/><button>保存发布记录</button></form><div class="release-row" v-for="x in releases" :key="x.id"><strong>{{x.version}}</strong><span>{{x.environment}}</span><span>{{x.status}}</span><code>{{x.commit_sha}}</code></div></section>
<section v-else><div class="table audit"><div v-for="x in audits" :key="x.id"><strong>{{x.action}}</strong><span>{{x.target_type}}</span><code>{{x.target_id}}</code><small>{{new Date(x.created_at).toLocaleString()}}</small></div></div><div v-if="!audits.length" class="empty">暂无审计记录</div></section></main></template>
<style scoped>main{padding:30px;min-height:100vh;background:#f5f7f8;color:#17211d}header small{color:#176f67;font-weight:800}h1{margin:4px 0}header p{color:#6d7873}nav{display:flex;flex-wrap:wrap;margin:22px 0;border-bottom:1px solid #ccd6d2}nav button{padding:11px 16px;border:0;background:none}nav button.active{color:#176f67;border-bottom:2px solid #176f67}.summary{display:grid;grid-template-columns:repeat(3,1fr);background:#fff;border:1px solid #dce3e0}.summary article{padding:18px;border-right:1px solid #ddd}.summary span,.summary strong{display:block}.summary strong{font-size:26px}.table{background:#fff;border:1px solid #dce3e0}.table>div{display:grid;grid-template-columns:2fr 1fr 1fr 2fr 1fr;gap:10px;padding:12px;border-bottom:1px solid #e5e9e7}.table i,.table em{font-style:normal}.table i.healthy,.table i.ok{color:#168072}.chips{display:flex;flex-wrap:wrap;gap:8px}.chips span{padding:8px;background:#e7f1ee}.note{padding:12px;background:#fff4d8}.audit>div{grid-template-columns:2fr 1fr 2fr 1.5fr}.empty{padding:50px;text-align:center;color:#78827e}pre{padding:15px;background:#17241f;color:#dbeae5;overflow:auto}.feedback-row,.release-row{display:grid;grid-template-columns:180px 1fr 120px;gap:12px;padding:12px;border-bottom:1px solid #dce3e0;background:#fff}.feedback-row p{margin:0}.release-form{display:grid;grid-template-columns:1fr 160px 1fr;gap:8px;margin-bottom:16px}.release-form input,.release-form select,.release-form textarea{padding:10px;border:1px solid #cbd6d2;border-radius:4px}.release-form textarea{grid-column:1/-1}.release-form button{justify-self:start;padding:10px 14px;border:0;border-radius:4px;background:#176f67;color:#fff}@media(max-width:720px){main{padding:76px 12px 20px}.summary{grid-template-columns:1fr}.table{overflow:auto}.table>div{min-width:700px}.feedback-row,.release-row,.release-form{grid-template-columns:1fr}.release-form textarea{grid-column:auto}}</style>
