<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{autonomyApi}from'@/api/autonomy'
const overview=ref<any>({}),forecast=ref<any>({chargeback:{},unit_economics:{}}),tab=ref('control'),lastPolicy=ref<any>(null)
const policy=reactive({key:'high-risk-action',name:'高风险行动策略',rules:{match:{risk:'high'}},test_cases:[{input:{risk:'high'},allow:true},{input:{risk:'low'},allow:false}]}),privacy=reactive({dataset_key:'anonymous-benchmark',period:new Date().toISOString().slice(0,7),epsilon_limit:2,delta:.00001,minimum_cohort:10}),drill=reactive({region:'cn-east',drill_type:'regional_failover',rpo_target_minutes:15,rto_target_minutes:60,actual_rpo_minutes:10,actual_rto_minutes:45,evidence:{runbook:'verified'},isolation_verified:true}),safety=reactive({target_type:'connector',target_id:'sandbox',scenario:'permission-drift-and-rollback',results:{sandbox:true},permission_drift:false,rollback_verified:true,score:90})
async function load(){[overview.value,forecast.value]=await Promise.all([autonomyApi.overview(),autonomyApi.forecast()])}
async function savePolicy(){lastPolicy.value=await autonomyApi.createPolicy(policy);ElMessage.success(lastPolicy.value.version.simulation.ready?'策略仿真通过':'策略仍被门禁阻断');await load()}
async function publish(){await autonomyApi.publishPolicy(lastPolicy.value.bundle.id,{version:1,canary_percent:10});ElMessage.success('策略已发布到 10% 灰度')}
async function savePrivacy(){await autonomyApi.privacyBudget(privacy);ElMessage.success('隐私预算已创建')}
async function saveDrill(){const x=await autonomyApi.recoveryDrill(drill);ElMessage[x.status==='passed'?'success':'error'](`灾备演练：${x.status}`);await load()}
async function saveSafety(){const x=await autonomyApi.safety(safety);ElMessage[x.gate_status==='passed'?'success':'error'](`安全门禁：${x.gate_status}`);await load()}
onMounted(load)
</script>
<template><main><header><div><small>AUTONOMY & COMPLIANCE</small><h1>自治与合规控制中心</h1><p>将审批、隐私、策略、灾备、财务和安全评测纳入同一生产证据链。</p></div><span class="gate">生产门禁</span></header><div class="metrics"><article v-for="(v,k) in overview" :key="k"><span>{{String(k).replaceAll('_',' ')}}</span><strong>{{v}}</strong></article></div><nav><button :class="{active:tab==='control'}" @click="tab='control'">策略与隐私</button><button :class="{active:tab==='resilience'}" @click="tab='resilience'">韧性与安全</button><button :class="{active:tab==='finops'}" @click="tab='finops'">FinOps</button></nav>
<section v-if="tab==='control'" class="grid"><form @submit.prevent="savePolicy"><h2>策略即代码</h2><label>策略标识<input v-model="policy.key" required pattern="[a-z0-9_-]+"/></label><label>名称<input v-model="policy.name" required/></label><div class="code">risk == high → require approval</div><p>内置 {{policy.test_cases.length}} 个仿真用例</p><div class="actions"><button>运行仿真</button><button v-if="lastPolicy?.version.simulation.ready" type="button" class="secondary" @click="publish">10% 灰度发布</button></div></form><form @submit.prevent="savePrivacy"><h2>差分隐私预算</h2><label>数据集<input v-model="privacy.dataset_key" required/></label><label>周期<input v-model="privacy.period" type="month"/></label><label>Epsilon 上限<input v-model.number="privacy.epsilon_limit" type="number" min="0.1" step="0.1"/></label><label>最小群组<input v-model.number="privacy.minimum_cohort" type="number" min="5"/></label><button>创建预算</button></form></section>
<section v-else-if="tab==='resilience'" class="grid"><form @submit.prevent="saveDrill"><h2>区域灾备演练</h2><label>区域<input v-model="drill.region"/></label><div class="pair"><label>RPO 目标<input v-model.number="drill.rpo_target_minutes" type="number"/></label><label>实际 RPO<input v-model.number="drill.actual_rpo_minutes" type="number"/></label></div><div class="pair"><label>RTO 目标<input v-model.number="drill.rto_target_minutes" type="number"/></label><label>实际 RTO<input v-model.number="drill.actual_rto_minutes" type="number"/></label></div><label class="check"><input v-model="drill.isolation_verified" type="checkbox"/>租户故障隔离已验证</label><button>记录演练</button></form><form @submit.prevent="saveSafety"><h2>自治决策安全评测</h2><label>评测场景<input v-model="safety.scenario"/></label><label>上线评分<input v-model.number="safety.score" type="number" min="0" max="100"/></label><label class="check"><input v-model="safety.permission_drift" type="checkbox"/>检测到权限漂移</label><label class="check"><input v-model="safety.rollback_verified" type="checkbox"/>回滚演练已验证</label><button>执行门禁</button></form></section>
<section v-else><div class="fin"><span>预测成本</span><strong>¥{{((forecast.forecast_cents||0)/100).toFixed(2)}}</strong><em :class="{danger:forecast.anomaly}">{{forecast.anomaly?'检测到异常':'成本正常'}}</em></div><h2>部门成本分摊</h2><div class="rows"><div v-for="(v,k) in forecast.chargeback" :key="k"><strong>{{k}}</strong><span>¥{{(Number(v)/100).toFixed(2)}}</span></div><p v-if="!Object.keys(forecast.chargeback||{}).length" class="empty">暂无财务账本记录</p></div></section></main></template>
<style scoped>main{min-height:100vh;padding:30px;background:#f4f7f6;color:#17231f}header{display:flex;justify-content:space-between}header small{color:#14756b;font-weight:800}h1{margin:4px 0}header p{margin:0;color:#69756f}.gate{height:fit-content;padding:7px 10px;border:1px solid #d4b667;background:#fff7d8;color:#755d13;border-radius:4px}.metrics{display:grid;grid-template-columns:repeat(6,1fr);margin-top:24px;background:#fff;border:1px solid #d8e1de}.metrics article{padding:15px;border-right:1px solid #e1e7e5}.metrics span,.metrics strong{display:block}.metrics span{text-transform:capitalize;color:#6f7d77;font-size:11px}.metrics strong{margin-top:5px;font-size:23px}nav{display:flex;margin:22px 0;border-bottom:1px solid #cdd8d4}nav button{padding:11px 15px;border:0;background:none}nav .active{color:#126f66;border-bottom:2px solid #126f66}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}form,.fin,.rows{padding:18px;background:#fff;border:1px solid #d7e0dd}form{display:grid;gap:11px}label{display:grid;gap:5px;font-size:12px;color:#63716b}input{box-sizing:border-box;width:100%;padding:10px;border:1px solid #c8d5d0;border-radius:4px}.check{display:flex;align-items:center}.check input{width:auto}button{cursor:pointer}form button{justify-self:start;padding:10px 14px;border:0;border-radius:4px;background:#176f67;color:#fff}.actions{display:flex;gap:8px}.actions .secondary{background:#26352f}.code{padding:15px;background:#17231f;color:#d9ebe5;font-family:monospace}.pair{display:grid;grid-template-columns:1fr 1fr;gap:10px}.fin{display:flex;align-items:center;gap:20px}.fin strong{font-size:28px}.fin em{margin-left:auto;color:#167064}.fin .danger{color:#b84040}.rows>div{display:flex;justify-content:space-between;padding:10px;border-bottom:1px solid #e2e8e5}.empty{text-align:center;color:#77827e}@media(max-width:900px){.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:720px){main{padding:76px 12px 20px}.grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}}</style>
