<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{commercialApi}from'@/api/commercial'
const tab=ref('overview'),overview=ref<any>({usage:[]}),templates=ref<any[]>([]),flows=ref<any[]>([]),cost=ref<any>({allocations:[],total_cents:0}),versions=ref<any[]>([]),selected=ref<any>(null)
const template=reactive({key:'',name:'',description:'',visibility:'private',definition:{steps:[]},change_note:'Initial version'}),flow=reactive({name:'',trigger:'high_risk_action',graph:{nodes:[{id:'request',label:'提交'},{id:'approve',label:'审批'}],edges:[{from:'request',to:'approve'}]},enabled:true}),sla=reactive({name:'高风险行动 SLA',target_type:'high_risk_action',target_minutes:120,warning_minutes:90,escalation_steps:[{after_minutes:90,role:'admin'}],enabled:true}),plan=reactive({plan_key:'enterprise',limits:{connector_executions:1000,actions:500},feature_flags:{connector_executions:true},status:'active'})
async function load(){[overview.value,templates.value,flows.value,cost.value]=await Promise.all([commercialApi.overview(),commercialApi.templates(),commercialApi.flows(),commercialApi.costReport()])}
async function addTemplate(){await commercialApi.createTemplate(template);ElMessage.success('模板 v1 已发布');template.key='';template.name='';await load()}
async function inspect(x:any){selected.value=x;versions.value=await commercialApi.versions(x.id)}
async function rollback(v:number){await commercialApi.rollback(selected.value.id,v);ElMessage.success(`已从 v${v} 创建回滚版本`);await inspect(selected.value);await load()}
async function addFlow(){await commercialApi.createFlow(flow);ElMessage.success('审批流已保存');flows.value=await commercialApi.flows()}
async function savePolicy(){await commercialApi.saveSla(sla);ElMessage.success('SLA 策略已保存')}
async function savePlan(){await commercialApi.saveEntitlement(plan);ElMessage.success('套餐限制已更新');await load()}
onMounted(load)
</script>
<template><main><header><div><small>DECISION OPERATIONS</small><h1>智能决策商业运营</h1><p>管理行动产品、审批、连接器、影响归因、SLA、基准、套餐与成本。</p></div><span class="status">运营中</span></header>
<nav><button v-for="x in [['overview','运营总览'],['templates','模板市场'],['approval','审批编排'],['sla','SLA 与套餐']]" :key="x[0]" :class="{active:tab===x[0]}" @click="tab=x[0]">{{x[1]}}</button></nav>
<section v-if="tab==='overview'"><div class="metrics"><article><span>行动模板</span><strong>{{overview.templates||0}}</strong></article><article><span>审批流</span><strong>{{overview.approval_flows||0}}</strong></article><article><span>连接器执行</span><strong>{{overview.connectors||0}}</strong></article><article><span>累计成本</span><strong>¥{{((cost.total_cents||0)/100).toFixed(2)}}</strong></article></div><h2>产品用量与成本分摊</h2><div class="table"><div class="head"><span>周期</span><span>功能</span><span>数量</span><span>成本</span></div><div v-for="x in cost.allocations" :key="x.id"><span>{{x.period}}</span><strong>{{x.feature}}</strong><span>{{x.quantity}}</span><span>¥{{(x.cost_cents/100).toFixed(2)}}</span></div><p v-if="!cost.allocations.length" class="empty">暂无计费用量</p></div></section>
<section v-else-if="tab==='templates'" class="split"><div><h2>行动模板市场</h2><div class="list"><button v-for="x in templates" :key="x.id" @click="inspect(x)"><span><strong>{{x.name}}</strong><small>{{x.key}} · {{x.visibility}}</small></span><b>v{{x.current_version}}</b></button><p v-if="!templates.length" class="empty">暂无模板</p></div><form @submit.prevent="addTemplate"><h3>发布模板</h3><input v-model="template.key" required pattern="[a-z0-9_-]+" placeholder="模板标识"/><input v-model="template.name" required placeholder="模板名称"/><textarea v-model="template.description" placeholder="适用范围"/><button class="primary">发布 v1</button></form></div><aside><h2>版本记录</h2><p v-if="!selected" class="empty">选择模板查看不可变版本</p><div v-for="v in versions" :key="v.id" class="version"><span><strong>v{{v.version}}</strong><small>{{v.change_note}}</small><code>{{v.checksum.slice(0,10)}}</code></span><button title="创建回滚版本" @click="rollback(v.version)">回滚</button></div></aside></section>
<section v-else-if="tab==='approval'" class="split"><div><h2>审批流</h2><div v-for="x in flows" :key="x.id" class="flow"><strong>{{x.name}}</strong><span>{{x.trigger}}</span><small>v{{x.version}}</small></div><p v-if="!flows.length" class="empty">暂无审批流</p></div><form @submit.prevent="addFlow"><h2>可视化编排</h2><input v-model="flow.name" required placeholder="审批流名称"/><div class="graph"><div v-for="(n,i) in flow.graph.nodes" :key="n.id" class="node">{{n.label}}<i v-if="i<flow.graph.nodes.length-1">→</i></div></div><label>触发条件<select v-model="flow.trigger"><option value="high_risk_action">高风险行动</option><option value="budget_overrun">预算超限</option><option value="external_execution">外部执行</option></select></label><button class="primary">保存审批流</button></form></section>
<section v-else class="split"><form @submit.prevent="savePolicy"><h2>SLA 升级策略</h2><input v-model="sla.name" required/><label>目标时限（分钟）<input v-model.number="sla.target_minutes" type="number" min="1"/></label><label>预警时限（分钟）<input v-model.number="sla.warning_minutes" type="number" min="1"/></label><button class="primary">保存 SLA</button></form><form @submit.prevent="savePlan"><h2>套餐与限制</h2><label>套餐<select v-model="plan.plan_key"><option>starter</option><option>business</option><option>enterprise</option></select></label><label>连接器月执行量<input v-model.number="plan.limits.connector_executions" type="number" min="0"/></label><label>行动月创建量<input v-model.number="plan.limits.actions" type="number" min="0"/></label><button class="primary">应用限制</button></form></section></main></template>
<style scoped>main{min-height:100vh;padding:30px;background:#f4f7f6;color:#18231f}header{display:flex;justify-content:space-between;align-items:flex-start}header small{color:#17756d;font-weight:800}h1{margin:4px 0;font-size:28px}header p{margin:0;color:#69756f}.status{padding:7px 10px;background:#dff2e9;color:#14715f;border:1px solid #b9dfd1;border-radius:4px}nav{display:flex;margin:24px 0;border-bottom:1px solid #cfd9d5}nav button{padding:11px 15px;border:0;background:none;cursor:pointer}nav button.active{color:#126f66;border-bottom:2px solid #126f66}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #d6dfdc;background:white}.metrics article{padding:18px;border-right:1px solid #e0e6e4}.metrics span,.metrics strong{display:block}.metrics strong{font-size:25px;margin-top:5px}.table,.list,.flow,form,aside{background:#fff;border:1px solid #d7e0dd}.table>div{display:grid;grid-template-columns:1fr 2fr 1fr 1fr;padding:12px;border-bottom:1px solid #e5eae8}.table .head{color:#71807a;font-size:12px}.split{display:grid;grid-template-columns:1.35fr 1fr;gap:18px}.split>div,.split>aside,form{padding:18px}.list button,.version,.flow{width:100%;display:flex;justify-content:space-between;align-items:center;padding:12px;border:0;border-bottom:1px solid #e2e8e5;background:#fff;text-align:left;cursor:pointer}.list span,.version span{display:grid;gap:3px}.list small,.version small,.flow span,.flow small{color:#71807a}form{display:grid;gap:10px;margin-top:16px}input,textarea,select{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd7d2;border-radius:4px}textarea{min-height:70px}.primary{justify-self:start;padding:10px 15px;border:0;border-radius:4px;background:#176f67;color:#fff;cursor:pointer}.graph{display:flex;align-items:center;min-height:110px;padding:15px;background:#f2f6f4}.node{position:relative;padding:12px;background:white;border:1px solid #aac9bf}.node i{position:absolute;right:-22px}.node+.node{margin-left:32px}.empty{padding:30px;text-align:center;color:#78847f}@media(max-width:760px){main{padding:76px 12px 20px}.metrics,.split{grid-template-columns:1fr}.metrics article{border-bottom:1px solid #e0e6e4}.table{overflow:auto}.table>div{min-width:560px}}</style>
