<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{enterpriseApi,selectTenant,type TenantContext}from'@/api/enterprise';import{platformApi}from'@/api/platform'
const tab=ref('overview'),loading=ref(true),ctx=ref<TenantContext|null>(null),overview=ref<any>({}),keys=ref<any[]>([]),apps=ref<any[]>([]),hooks=ref<any[]>([]),deliveries=ref<any[]>([]),market=ref<any[]>([]),installs=ref<any[]>([]),usage=ref<any>({}),secret=ref(''),sandboxResult=ref<any>(null)
const keyForm=reactive({name:'',scopes:['events:read'],workspace_id:null as string|null}),appForm=reactive({name:'',app_type:'public',redirect_uris:'https://app.example/callback',scopes:['events:read']}),hookForm=reactive({name:'',target_url:'',event_types:['event.created']}),installForm=reactive({connector_key:'slack',credential_reference:'vault://tenant/integration',workspace_id:null as string|null}),sandbox=reactive({operation:'list_events',input:{limit:5}})
const can=(p:string)=>ctx.value?.permissions.includes(p),percent=computed(()=>usage.value.plan?Math.min(100,Math.round(usage.value.used/usage.value.plan.limit*100)):0)
async function load(){loading.value=true;try{ctx.value=await enterpriseApi.context();selectTenant(ctx.value.organization.id,ctx.value.workspaces[0]?.id);[overview.value,keys.value,apps.value,hooks.value,deliveries.value,market.value,installs.value,usage.value]=await Promise.all([platformApi.overview(),platformApi.keys(),platformApi.apps(),platformApi.webhooks(),platformApi.deliveries(),platformApi.marketplace(),platformApi.installations(),platformApi.usage()])}finally{loading.value=false}}
async function addKey(){const r=await platformApi.createKey(keyForm);secret.value=r.secret;keyForm.name='';keys.value=await platformApi.keys();ElMessage.success('API Key 已创建，仅展示一次')}
async function addApp(){const r=await platformApi.createApp({...appForm,redirect_uris:appForm.redirect_uris.split('\n').filter(Boolean)});secret.value=r.client_secret||r.client_id;apps.value=await platformApi.apps();ElMessage.success('应用已提交安全审查')}
async function addHook(){const r=await platformApi.createWebhook(hookForm);secret.value=r.secret;hooks.value=await platformApi.webhooks();ElMessage.success('Webhook 已创建')}
async function testHook(id:string){sandboxResult.value=await platformApi.testWebhook(id);deliveries.value=await platformApi.deliveries();ElMessage.success('已生成 Sandbox 签名报文，未外发')}
async function install(){const r=await platformApi.install(installForm);installs.value=await platformApi.installations();ElMessage.success(r.approval_required?'安装已进入管理员审批':'连接器已安装')}
async function decide(kind:'app'|'install',id:string,decision:string){const data={decision,findings:[]};if(kind==='app'){await platformApi.reviewApp(id,data);apps.value=await platformApi.apps()}else{await platformApi.reviewInstall(id,data);installs.value=await platformApi.installations()}}
async function runSandbox(){sandboxResult.value=await platformApi.sandbox(sandbox)}
onMounted(load)
</script>
<template><main class="developer"><header><div><small>OPEN PLATFORM</small><h1>开发者平台</h1><p>在租户边界内授权应用、管理集成、验证事件投递并控制 API 成本。</p></div><div v-if="ctx" class="tenant"><strong>{{ctx.organization.name}}</strong><span>{{ctx.membership.role_key}} · {{ctx.organization.data_region}}</span></div></header>
<div v-if="loading" class="state">正在加载开发者上下文...</div><template v-else><nav><button v-for="x in [['overview','概览'],['keys','API Keys'],['oauth','OAuth 应用'],['webhooks','Webhooks'],['market','集成市场'],['usage','用量与账单'],['sandbox','Sandbox'],['docs','文档与 SDK']]" :class="{active:tab===x[0]}" @click="tab=x[0]">{{x[1]}}</button></nav>
<aside v-if="secret" class="secret"><div><strong>仅展示一次</strong><code>{{secret}}</code></div><button @click="navigator.clipboard.writeText(secret);ElMessage.success('已复制')">复制</button><button @click="secret=''">关闭</button></aside>
<section v-if="tab==='overview'"><div class="metrics"><article><span>有效密钥</span><strong>{{overview.api_keys}}</strong></article><article><span>OAuth 应用</span><strong>{{overview.oauth_apps}}</strong></article><article><span>Webhook</span><strong>{{overview.webhooks}}</strong></article><article><span>连接器</span><strong>{{overview.installations}}</strong></article></div><div class="notice"><strong>Sandbox 隔离已启用</strong><span>禁止真实外发、私有知识读取和生产写入。</span></div></section>
<section v-else-if="tab==='keys'"><h2>租户 API Keys</h2><form v-if="can('developer.manage')" @submit.prevent="addKey" class="form"><input v-model="keyForm.name" required placeholder="密钥名称"><select v-model="keyForm.scopes" multiple><option v-for="s in ['events:read','search:read','reports:read','reports:write','webhooks:read','webhooks:write','knowledge:read','agent:run']">{{s}}</option></select><button>创建密钥</button></form><div class="rows"><div v-for="x in keys"><strong>{{x.name}}</strong><code>{{x.prefix}}...</code><span>{{x.scopes.join(' · ')}}</span><button v-if="!x.revoked_at&&can('developer.manage')" class="danger" @click="platformApi.revokeKey(x.id).then(load)">撤销</button></div></div></section>
<section v-else-if="tab==='oauth'"><h2>OAuth 2.1 应用</h2><form v-if="can('developer.manage')" @submit.prevent="addApp" class="form"><input v-model="appForm.name" required placeholder="应用名称"><select v-model="appForm.app_type"><option value="public">Public + PKCE</option><option value="confidential">Confidential + PKCE</option></select><textarea v-model="appForm.redirect_uris" required></textarea><button>注册应用</button></form><div class="rows"><div v-for="x in apps"><strong>{{x.name}}</strong><code>{{x.client_id}}</code><span>{{x.review_status}}</span><span class="actions"><button v-if="x.review_status==='pending'&&can('integrations.approve')" @click="decide('app',x.id,'approved')">批准</button><button v-if="!x.revoked_at&&can('developer.manage')" class="danger" @click="platformApi.revokeApp(x.id).then(load)">撤销</button></span></div></div></section>
<section v-else-if="tab==='webhooks'"><h2>Webhook 订阅</h2><form v-if="can('developer.manage')" @submit.prevent="addHook" class="form"><input v-model="hookForm.name" required placeholder="端点名称"><input v-model="hookForm.target_url" required type="url" placeholder="https://hooks.example.com/infopulse"><select v-model="hookForm.event_types" multiple><option v-for="x in ['event.created','event.risk_changed','report.ready','alert.triggered','task.failed']">{{x}}</option></select><button>新增端点</button></form><div class="rows"><div v-for="x in hooks"><strong>{{x.name}}</strong><span>{{x.target_url}}</span><span>{{x.event_types.join(' · ')}}</span><button @click="testHook(x.id)">测试签名</button></div></div><h3>投递与重放</h3><div class="rows"><div v-for="x in deliveries"><strong>{{x.event_type}}</strong><code>{{x.event_id}}</code><span>{{x.status}} · attempt {{x.attempt}}</span><button v-if="can('developer.manage')" @click="platformApi.replay(x.id).then(load)">重放</button></div></div></section>
<section v-else-if="tab==='market'"><h2>集成市场</h2><form v-if="can('integrations.install')" @submit.prevent="install" class="form"><select v-model="installForm.connector_key"><option v-for="x in market" :value="x.key">{{x.name}}</option></select><input v-model="installForm.credential_reference" required placeholder="vault://tenant/secret"><button>申请安装</button></form><div class="catalog"><article v-for="x in market"><strong>{{x.name}}</strong><span>{{x.category}}</span><p>{{x.capabilities.join(' · ')}}</p><small>{{x.write_capable?'外部写入需审批':'只读安装'}}</small></article></div><h3>已申请安装</h3><div class="rows"><div v-for="x in installs"><strong>{{x.connector_key}}</strong><span>{{x.credential_reference}}</span><span>{{x.status}}</span><span class="actions"><button v-if="x.status==='pending'&&can('integrations.approve')" @click="decide('install',x.id,'approved')">批准</button><button v-if="x.status!=='revoked'&&can('integrations.install')" class="danger" @click="platformApi.revokeInstall(x.id).then(load)">撤销</button></span></div></div></section>
<section v-else-if="tab==='usage'"><h2>API 用量与套餐</h2><div class="usage"><strong>{{usage.used?.toLocaleString()}} / {{usage.plan?.limit?.toLocaleString()}}</strong><progress :value="percent" max="100"></progress><span>{{usage.period}} · {{usage.plan?.name}} · 剩余 {{usage.remaining?.toLocaleString()}}</span></div><div class="rows"><div v-for="x in usage.by_scope"><strong>{{x.scope}}</strong><span>{{x.requests.toLocaleString()}} requests</span></div></div></section>
<section v-else-if="tab==='sandbox'"><h2>隔离 Sandbox</h2><form @submit.prevent="runSandbox" class="form"><select v-model="sandbox.operation"><option value="list_events">列出事件</option><option value="search">搜索</option><option value="render_webhook">渲染 Webhook</option></select><button>运行</button></form><pre v-if="sandboxResult">{{JSON.stringify(sandboxResult,null,2)}}</pre></section>
<section v-else><h2>OpenAPI 与官方 SDK</h2><div class="doclinks"><a href="/openapi.json" target="_blank">OpenAPI JSON</a><a href="/docs" target="_blank">交互式 API 文档</a><code>sdk/python · infopulse-sdk</code><code>sdk/typescript · @infopulse/sdk</code></div><p>SDK 已内置租户头、分页、超时、幂等键、稳定错误解析和 Webhook 验签。生产连接器需要供应商真实账号及 Vault 引用。</p></section></template></main></template>
<style scoped>.developer{padding:30px;min-height:100vh;background:#f4f6f5;color:#18221e}.developer>header{display:flex;justify-content:space-between;align-items:end;gap:20px}.developer small{color:#197268;font-weight:800}.developer h1{margin:5px 0;font-size:32px}.developer p{color:#64706b}.tenant{text-align:right}.tenant strong,.tenant span{display:block}nav{display:flex;overflow:auto;border-bottom:1px solid #cad5d0;margin:24px 0}nav button{white-space:nowrap;border:0;background:none;padding:12px 15px}nav button.active{color:#116d62;border-bottom:2px solid #116d62}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #d6dfdb;background:white}.metrics article{padding:18px;border-right:1px solid #e0e6e3}.metrics span,.metrics strong{display:block}.metrics strong{font-size:25px}.notice{margin-top:20px;border-left:3px solid #197268;background:#e8f2ee;padding:15px}.notice span{display:block;color:#56655f}.secret{display:flex;align-items:center;gap:12px;background:#17241f;color:white;padding:13px;margin-bottom:18px}.secret div{display:grid;flex:1}.secret code{overflow:auto;user-select:all}.form{display:grid;grid-template-columns:1.2fr 1.8fr auto;gap:10px;margin:15px 0;max-width:950px}input,select,textarea{min-width:0;padding:10px;border:1px solid #bdc9c4;border-radius:4px;background:white}select[multiple],textarea{min-height:78px}button,.doclinks a{border:0;border-radius:4px;background:#dfe8e4;color:#173c35;padding:9px 13px;cursor:pointer;text-decoration:none}form button,.actions button:first-child{background:#176f67;color:white}.danger{background:#a13b43!important;color:white}.rows{border-top:1px solid #d3dcd8}.rows>div{display:grid;grid-template-columns:minmax(130px,1fr) minmax(170px,2fr) minmax(150px,2fr) auto;gap:12px;align-items:center;padding:13px 4px;border-bottom:1px solid #d3dcd8}.actions{display:flex;gap:6px}.catalog{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:#d4ded9;border:1px solid #d4ded9}.catalog article{background:white;padding:15px}.catalog strong,.catalog span,.catalog small{display:block}.catalog span{color:#197268}.usage{display:grid;gap:12px;max-width:800px}.usage strong{font-size:25px}.usage progress{width:100%}pre{background:#17241f;color:#dceae4;padding:16px;overflow:auto;max-height:480px}.doclinks{display:flex;flex-wrap:wrap;gap:10px}.state{padding:60px;text-align:center}@media(max-width:760px){.developer{padding:76px 12px 24px}.tenant{display:none}.metrics{grid-template-columns:1fr 1fr}.form{grid-template-columns:1fr}.rows{overflow:auto}.rows>div{min-width:680px}.catalog{grid-template-columns:1fr 1fr}.secret{align-items:start;flex-wrap:wrap}.secret div{flex-basis:100%}}</style>
