<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{enterpriseApi,selectTenant,type TenantContext}from'@/api/enterprise'
const loading=ref(true),tab=ref('overview'),ctx=ref<TenantContext|null>(null),members=ref<any[]>([]),roles=ref<any[]>([]),providers=ref<any[]>([]),approvals=ref<any[]>([]),policy=ref<any>({}),quota=ref<any>({}),ops=ref<any>({members:{},model_tokens:{},model_cost:{}}),scimToken=ref(''),teamName=ref('')
const member=reactive({email:'',role_key:'member',workspace_ids:[] as string[]}),role=reactive({key:'',name:'',permissions:['org.read'] as string[]}),provider=reactive({provider_type:'oidc',name:'',issuer:'',client_id:'',enabled:false}),approval=reactive({action_type:'bulk_export',risk_level:'high',payload:{}}),hold=reactive({name:'',reason:'',scope:{all:true}})
const can=(permission:string)=>Boolean(ctx.value?.permissions.includes(permission));const percent=(used=0,limit=1)=>Math.min(100,Math.round(used/Math.max(limit,1)*100))
async function load(){loading.value=true;try{ctx.value=await enterpriseApi.context();selectTenant(ctx.value.organization.id,ctx.value.workspaces[0]?.id);[members.value,roles.value,providers.value,approvals.value,policy.value,quota.value,ops.value]=await Promise.all([enterpriseApi.members(),enterpriseApi.roles(),enterpriseApi.providers().catch(()=>[]),enterpriseApi.approvals(),enterpriseApi.policy(),enterpriseApi.quota(),enterpriseApi.operations()])}finally{loading.value=false}}
async function addMember(){await enterpriseApi.addMember(member);member.email='';members.value=await enterpriseApi.members();ElMessage.success('成员已加入组织')}
async function addRole(){await enterpriseApi.createRole(role);role.key='';role.name='';roles.value=await enterpriseApi.roles();ElMessage.success('角色已创建')}
async function addTeam(){await enterpriseApi.createTeam({name:teamName.value,description:'',user_ids:[]});teamName.value='';ElMessage.success('团队已创建')}
async function addProvider(){const metadata:any={};if(provider.provider_type==='oidc'){metadata.authorization_endpoint=provider.issuer.replace(/\/$/,'')+'/authorize';metadata.jwks_uri=provider.issuer.replace(/\/$/,'')+'/.well-known/jwks.json'}if(provider.provider_type==='saml'){metadata.sso_url=provider.issuer;metadata.signing_certificate=''}await enterpriseApi.createProvider({...provider,metadata});providers.value=await enterpriseApi.providers();ElMessage.success('身份源已保存')}
async function rotate(id:string){scimToken.value=(await enterpriseApi.rotateScim(id)).token}
async function requestApproval(){await enterpriseApi.requestApproval(approval);approvals.value=await enterpriseApi.approvals();ElMessage.success('审批申请已提交')}
async function decide(id:string,decision:string){await enterpriseApi.decide(id,{decision,note:'已由企业治理控制台复核'});approvals.value=await enterpriseApi.approvals()}
async function savePolicy(){await enterpriseApi.updatePolicy(policy.value);ElMessage.success('安全策略已更新')}
async function saveQuota(){await enterpriseApi.updateQuota(quota.value);ops.value=await enterpriseApi.operations();ElMessage.success('配额已更新')}
async function addHold(){await enterpriseApi.createLegalHold(hold);hold.name='';hold.reason='';ElMessage.success('法律保留已生效')}
onMounted(load)
</script>

<template><main class="enterprise"><header><div><small>ENTERPRISE GOVERNANCE</small><h1>企业治理</h1><p>在组织边界内管理身份、权限、审批、合规、成本与服务等级。</p></div><div v-if="ctx" class="tenant"><strong>{{ctx.organization.name}}</strong><span>{{ctx.organization.data_region.toUpperCase()}} · {{ctx.membership.role_key}}</span></div></header>
<div v-if="loading" class="state">正在加载企业上下文...</div><template v-else-if="ctx"><nav aria-label="企业治理视图"><button v-for="item in [['overview','运营概览'],['members','成员团队'],['roles','角色权限'],['identity','身份与 SCIM'],['approvals','审批'],['policy','安全合规'],['cost','配额与 SLA']]" :key="item[0]" :class="{active:tab===item[0]}" @click="tab=item[0]">{{item[1]}}</button></nav>

<section v-if="tab==='overview'"><div class="metrics"><article><span>成员</span><strong>{{ops.members.used||0}} / {{ops.members.limit||0}}</strong></article><article><span>模型 Token</span><strong>{{(ops.model_tokens.used||0).toLocaleString()}}</strong></article><article><span>本月成本</span><strong>¥{{Number(ops.model_cost.used||0).toFixed(2)}}</strong></article><article><span>数据驻留</span><strong>{{ops.data_region?.toUpperCase()}}</strong></article></div><div class="band"><h2>Workspace</h2><div class="rows"><div v-for="x in ctx.workspaces" :key="x.id"><strong>{{x.name}}</strong><code>{{x.slug}}</code><span>{{x.status}}</span></div></div></div><div class="band"><h2>租户 SLA</h2><div v-if="ops.sla" class="sla"><strong>{{ops.sla.availability}}%</strong><span>P95 {{ops.sla.p95_latency_ms}} ms</span><span>错误预算 {{ops.sla.error_budget_remaining}}%</span><span>{{ops.sla.incidents}} 次事故</span></div><p v-else class="empty">尚无已结算的租户 SLA 周期。</p></div></section>

<section v-else-if="tab==='members'"><h2>成员与团队</h2><p>只有已有 InfoPulse 账号可被加入，Workspace 授权不会跨组织。</p><form v-if="can('members.manage')" @submit.prevent="addMember" class="formline"><input v-model="member.email" required type="email" placeholder="成员邮箱"><select v-model="member.role_key"><option v-for="x in roles" :key="x.key" :value="x.key">{{x.name}}</option></select><button>添加成员</button></form><div class="rows"><div v-for="x in members" :key="x.id"><strong>{{x.username}}</strong><span>{{x.email}}</span><code>{{x.role_key}}</code><i>{{x.status}}</i></div></div><form v-if="can('members.manage')" @submit.prevent="addTeam" class="formline compact"><input v-model="teamName" required placeholder="新团队名称"><button>创建空团队</button></form></section>

<section v-else-if="tab==='roles'"><h2>自定义角色</h2><p class="notice">权限来自固定白名单，不能提交任意权限字符串。</p><form v-if="can('roles.manage')" @submit.prevent="addRole" class="formgrid"><label>角色标识<input v-model="role.key" required pattern="[a-z][a-z0-9_.-]{1,39}"></label><label>显示名称<input v-model="role.name" required></label><label class="wide">权限<select v-model="role.permissions" multiple><option value="org.read">查看组织</option><option value="members.manage">管理成员</option><option value="approvals.request">提交审批</option><option value="approvals.decide">审批决策</option><option value="audit.export">导出审计</option><option value="billing.read">查看成本</option><option value="sla.read">查看 SLA</option></select></label><button>创建角色</button></form><div class="rows roles"><div v-for="x in roles" :key="x.id"><strong>{{x.name}}</strong><code>{{x.key}}</code><span>{{x.permissions.join(' · ')}}</span><i>{{x.is_system?'内置':'自定义'}}</i></div></div></section>

<section v-else-if="tab==='identity'"><h2>SSO、SAML、OIDC 与 SCIM</h2><p class="notice">仅保存公开协议元数据；客户端密钥和私钥必须由生产 Secret 管理器注入。</p><form v-if="can('sso.manage')" @submit.prevent="addProvider" class="formgrid"><label>协议<select v-model="provider.provider_type"><option value="oidc">OIDC</option><option value="saml">SAML</option><option value="scim">SCIM 2.0</option></select></label><label>名称<input v-model="provider.name" required></label><label>Issuer / SSO URL<input v-model="provider.issuer" :required="provider.provider_type!=='scim'" placeholder="https://id.example.com"></label><label>Client ID<input v-model="provider.client_id"></label><label class="check"><input v-model="provider.enabled" type="checkbox">验证后启用</label><button>保存身份源</button></form><div class="rows"><div v-for="x in providers" :key="x.id"><strong>{{x.name}}</strong><code>{{x.provider_type.toUpperCase()}}</code><span>{{x.enabled?'已启用':'未启用'}}</span><button v-if="x.provider_type==='scim'" @click="rotate(x.id)">轮换令牌</button></div></div><div v-if="scimToken" class="secret"><strong>仅显示一次</strong><code>{{scimToken}}</code><button @click="scimToken=''">关闭</button></div></section>

<section v-else-if="tab==='approvals'"><h2>高风险操作审批</h2><form v-if="can('approvals.request')" @submit.prevent="requestApproval" class="formline"><select v-model="approval.action_type"><option value="bulk_export">批量导出</option><option value="external_webhook">外部 Webhook</option><option value="delete_workspace">删除 Workspace</option><option value="change_data_region">变更驻留区域</option><option value="raise_model_budget">提高模型预算</option></select><select v-model="approval.risk_level"><option>medium</option><option>high</option><option>critical</option></select><button>提交审批</button></form><div class="rows"><div v-for="x in approvals" :key="x.id"><strong>{{x.action_type}}</strong><span>{{x.risk_level}}</span><code>{{x.status}}</code><span v-if="x.status==='pending'&&can('approvals.decide')" class="actions"><button @click="decide(x.id,'approved')">批准</button><button class="danger" @click="decide(x.id,'rejected')">拒绝</button></span></div></div></section>

<section v-else-if="tab==='policy'"><h2>安全与合规策略</h2><form @submit.prevent="savePolicy" class="formgrid"><label class="check"><input v-model="policy.require_sso" type="checkbox">强制企业 SSO</label><label class="check"><input v-model="policy.require_mfa" type="checkbox">要求 MFA</label><label class="check"><input v-model="policy.approval_for_high_risk" type="checkbox">高风险操作必须审批</label><label>会话时长（分钟）<input v-model.number="policy.session_minutes" type="number" min="15" max="1440"></label><label>数据保留（天）<input v-model.number="policy.retention_days" type="number" min="30" max="3650"></label><button v-if="can('policy.manage')">保存策略</button></form><div class="compliance"><button v-if="can('audit.export')" @click="enterpriseApi.auditExport()">导出审计 JSON</button><form v-if="can('legal_hold.manage')" @submit.prevent="addHold" class="formline"><input v-model="hold.name" required placeholder="法律保留名称"><input v-model="hold.reason" required placeholder="保留原因"><button>启用法律保留</button></form></div></section>

<section v-else><h2>租户配额、成本与 SLA</h2><div class="bars"><label>成员 <span>{{ops.members.used}} / {{ops.members.limit}}</span><progress :value="percent(ops.members.used,ops.members.limit)" max="100"/></label><label>模型 Token <span>{{ops.model_tokens.used}} / {{ops.model_tokens.limit}}</span><progress :value="percent(ops.model_tokens.used,ops.model_tokens.limit)" max="100"/></label><label>模型成本 <span>{{ops.model_cost.used}} / {{ops.model_cost.limit}}</span><progress :value="percent(ops.model_cost.used,ops.model_cost.limit)" max="100"/></label></div><form v-if="can('billing.manage')" @submit.prevent="saveQuota" class="formgrid"><label>成员上限<input v-model.number="quota.member_limit" type="number"></label><label>存储字节<input v-model.number="quota.storage_bytes" type="number"></label><label>月 Token 预算<input v-model.number="quota.monthly_model_tokens" type="number"></label><label>月成本上限<input v-model.number="quota.monthly_cost_limit" type="number"></label><label>预警阈值 %<input v-model.number="quota.alert_at_percent" type="number"></label><button>更新配额</button></form><p class="notice">单次提高成本上限超过 2 倍会被拒绝，必须先获得 raise_model_budget 审批。</p></section>
</template></main></template>

<style scoped>.enterprise{padding:30px;min-height:100vh;background:#f4f6f5;color:#18221e}.enterprise>header{display:flex;justify-content:space-between;gap:20px;align-items:end}.enterprise small{color:#197268;font-weight:800}.enterprise h1{margin:5px 0;font-size:32px}.enterprise h2{font-size:19px}.enterprise p{color:#64706b}.tenant{text-align:right}.tenant strong,.tenant span{display:block}.tenant span{color:#68746f;font-size:13px}nav{display:flex;overflow:auto;border-bottom:1px solid #cad5d0;margin:24px 0}nav button{white-space:nowrap;border:0;background:none;padding:12px 15px}nav button.active{color:#116d62;border-bottom:2px solid #116d62}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #d6dfdb;background:#fff}.metrics article{padding:18px;border-right:1px solid #e0e6e3}.metrics span,.metrics strong{display:block}.metrics strong{font-size:24px;margin-top:5px}.band{margin-top:24px}.rows{border-top:1px solid #d3dcd8}.rows>div{display:grid;grid-template-columns:minmax(150px,1fr) minmax(140px,2fr) minmax(100px,1fr) auto;gap:12px;align-items:center;padding:13px 5px;border-bottom:1px solid #d3dcd8}.rows i{font-style:normal;color:#537069}.formline,.formgrid{display:grid;gap:10px;margin:16px 0}.formline{grid-template-columns:2fr 1fr auto}.formline.compact{grid-template-columns:2fr auto;max-width:540px}.formgrid{grid-template-columns:repeat(2,minmax(0,1fr));max-width:820px}.formgrid label{display:grid;gap:5px;color:#53615b}.formgrid .wide{grid-column:1/-1}.formgrid select[multiple]{min-height:120px}.formgrid .check{display:flex;align-items:center;gap:8px}.formgrid button{justify-self:start}input,select{min-width:0;padding:10px;border:1px solid #bfcac5;border-radius:4px;background:#fff}button{padding:9px 13px;border:0;border-radius:4px;background:#dfe8e4;color:#173c35;cursor:pointer}form>button,.actions button:first-child{background:#176f67;color:#fff}.danger{background:#a13b43!important;color:#fff}.notice{padding:11px 13px;background:#fff5d9;border-left:3px solid #c88a18}.secret{display:flex;align-items:center;gap:12px;padding:12px;background:#18231f;color:#e6f0ec;overflow:auto}.secret code{user-select:all}.bars{display:grid;gap:16px;max-width:780px}.bars label{display:grid;grid-template-columns:160px 1fr;gap:8px}.bars progress{grid-column:1/-1;width:100%;height:10px}.sla{display:flex;gap:24px;align-items:baseline}.sla strong{font-size:30px;color:#176f67}.state,.empty{padding:50px 0;text-align:center;color:#6e7974}@media(max-width:760px){.enterprise{padding:76px 12px 24px}.enterprise>header{align-items:start}.tenant{display:none}.metrics{grid-template-columns:1fr 1fr}.rows{overflow:auto}.rows>div{min-width:660px}.formline,.formline.compact,.formgrid{grid-template-columns:1fr}.formgrid .wide{grid-column:auto}.sla{align-items:start;flex-direction:column;gap:6px}}</style>
