<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{enterpriseApi,selectTenant,type TenantContext}from'@/api/enterprise';import{globalIntelligenceApi as api}from'@/api/globalIntelligence'
const tab=ref('overview'),loading=ref(true),ctx=ref<TenantContext|null>(null),cap=ref<any>({}),narratives=ref<any[]>([]),scenarios=ref<any[]>([]),room=ref<any>(),translations=ref<any[]>([]),eventId=ref(''),contentId=ref(''),target=ref('zh'),roomId=ref(''),tabs=[['overview','全球态势'],['translation','引用级翻译'],['narratives','叙事与信号'],['scenario','情景推演'],['decision','决策室'],['quality','质量与回测']]
const scenario=reactive({name:'',assumptions:'',evidence:''}),newRoom=reactive({name:''}),option=reactive({title:'',constraints:'',benefits:'',effects:'',evidence:''});const regions=computed(()=>Object.entries(narratives.value.flatMap(x=>x.regions||[]).reduce((a:any,x:string)=>{a[x]=(a[x]||0)+1;return a},{})))
const can=(p:string)=>ctx.value?.permissions.includes(p),list=(x:string)=>x.split('\n').map(x=>x.trim()).filter(Boolean),ids=(x:string)=>x.split(',').map(x=>x.trim()).filter(Boolean)
async function load(){loading.value=true;try{ctx.value=await enterpriseApi.context();selectTenant(ctx.value.organization.id,ctx.value.workspaces[0]?.id);[cap.value,narratives.value,scenarios.value]=await Promise.all([api.capabilities(),api.narratives(),api.scenarios()])}finally{loading.value=false}}
async function getTranslations(){translations.value=await api.translations(contentId.value)}async function translate(){const x=await api.translate(contentId.value,target.value);translations.value=[...translations.value,x];ElMessage.success('已保存带原始内容引用的翻译')}
async function build(){const x=await api.buildNarratives({event_id:eventId.value,workspace_id:ctx.value?.workspaces[0]?.id});narratives.value=x.items;if(!x.items.length)ElMessage.info(x.empty_reason)}
async function makeScenario(){const x=await api.createScenario({event_id:eventId.value,workspace_id:ctx.value?.workspaces[0]?.id,name:scenario.name,assumptions:list(scenario.assumptions),evidence_content_ids:ids(scenario.evidence)});scenarios.value=[x,...scenarios.value];ElMessage.success('情景已创建，影响链不代表预测')}
async function makeRoom(){const x=await api.createRoom({event_id:eventId.value,workspace_id:ctx.value?.workspaces[0]?.id,name:newRoom.name});room.value=await api.room(x.id);roomId.value=x.id}async function openRoom(){room.value=await api.room(roomId.value)}async function addOption(){await api.addOption(room.value.id,{title:option.title,constraints:list(option.constraints),benefits:list(option.benefits),side_effects:list(option.effects),evidence_content_ids:ids(option.evidence)});await openRoom()}async function freeze(){await api.freeze(room.value.id,'Evidence and options reviewed in decision room');await openRoom();ElMessage.success('决策室已冻结')}
onMounted(load)
</script>
<template><main class="global"><header><div><small>GLOBAL INTELLIGENCE</small><h1>跨语言全球情报与决策推演</h1><p>原文、翻译、叙事、推演和决策都回溯到来源证据。</p></div><div class="tenant" v-if="ctx">{{ctx.organization.name}} · {{ctx.organization.data_region}}</div></header><nav><button v-for="x in tabs" :class="{active:tab===x[0]}" @click="tab=x[0]">{{x[1]}}</button></nav><div v-if="loading" class="empty">正在加载全球情报...</div><template v-else>
<section v-if="tab==='overview'"><div class="metrics"><article><span>跨语言叙事</span><strong>{{narratives.length}}</strong></article><article><span>地域覆盖</span><strong>{{regions.length}}</strong></article><article><span>情景</span><strong>{{scenarios.length}}</strong></article><article><span>虚假结论</span><strong>禁止</strong></article></div><div class="map"><div class="world"><b>全球区域视图</b><span v-for="x in regions" :style="{width:Math.max(18,Number(x[1])*34)+'px'}">{{x[0]}} {{x[1]}}</span><p v-if="!regions.length">没有带地域证据的跨语言叙事。</p></div><div><h2>时间线</h2><ol><li v-for="x in narratives"><time>{{x.languages.join(' / ')}}</time><strong>{{x.title}}</strong><span>{{x.regions.join(' · ')||'未提供地域'}}</span></li></ol></div></div></section>
<section v-else-if="tab==='translation'"><h2>引用级翻译</h2><p>翻译保留原始内容 ID、源语言、目标语言和模型版本；无批准模型时明确失败。</p><form @submit.prevent="getTranslations"><input v-model="contentId" required placeholder="原始内容 ID"><button>查看翻译</button></form><form @submit.prevent="translate"><select v-model="target"><option>zh</option><option>en</option><option>ja</option><option>ar</option><option>ru</option></select><button v-if="can('global.translate')">生成真实翻译</button></form><article v-for="x in translations" class="translation"><small>{{x.source_language}} → {{x.target_language}} · {{x.model_name}}</small><h3>{{x.title}}</h3><p>{{x.body}}</p><code>content: {{x.content_item_id}}</code></article></section>
<section v-else-if="tab==='narratives'"><h2>跨语言叙事、地域与文化语境</h2><form @submit.prevent="build"><input v-model="eventId" required placeholder="事件 ID"><button v-if="can('global.analyze')">基于证据聚类</button></form><div class="rows"><article v-for="x in narratives"><div><strong>{{x.title}}</strong><span>{{x.languages.join(' / ')}} · {{x.regions.join(' · ')||'地域未知'}}</span><small>证据 {{x.content_item_ids.length}} 条 · 置信度 {{x.confidence}}</small></div><aside><b v-for="s in x.signals">{{s.type}} · {{s.status}}</b><p v-for="s in x.signals">{{s.explanation}}</p><i v-if="!x.signals.length">未发现需复核的规则信号</i></aside></article></div></section>
<section v-else-if="tab==='scenario'"><h2>情景假设与影响链</h2><p>至少两条事件来源才可建立情景；它呈现假设与证据缺口，不是预测。</p><form class="stack" @submit.prevent="makeScenario"><input v-model="eventId" required placeholder="事件 ID"><input v-model="scenario.name" required placeholder="情景名称"><textarea v-model="scenario.assumptions" required placeholder="每行一个假设"></textarea><input v-model="scenario.evidence" required placeholder="证据内容 ID，以逗号分隔"><button v-if="can('global.analyze')">创建证据受限情景</button></form><article v-for="x in scenarios" class="scenario"><h3>{{x.name}} <small>{{x.status}}</small></h3><p>假设：{{x.assumptions.join('；')}}</p><ol><li v-for="s in x.impact_chain">{{s.claim}}</li></ol><b v-for="g in x.evidence_gaps">证据缺口：{{g}}</b></article></section>
<section v-else-if="tab==='decision'"><div v-if="!room"><h2>多人决策室</h2><form @submit.prevent="makeRoom"><input v-model="eventId" required placeholder="事件 ID"><input v-model="newRoom.name" required placeholder="决策室名称"><button v-if="can('decision.write')">创建</button></form><form @submit.prevent="openRoom"><input v-model="roomId" required placeholder="已有决策室 ID"><button>打开</button></form></div><template v-else><div class="head"><div><h2>{{room.name}}</h2><p>{{room.status}} · 事件 {{room.event_id}}</p></div><button v-if="room.status==='open'&&can('decision.freeze')" @click="freeze">冻结结论</button></div><div class="decision"><div><h3>决策选项</h3><article v-for="x in room.options"><strong>{{x.title}}</strong><p>收益：{{x.benefits.join('；')||'未填写'}}</p><p>副作用：{{x.side_effects.join('；')||'未填写'}}</p><b>反事实：{{x.counterfactuals.join('；')}}</b><ul><li v-for="q in x.red_team_questions">{{q}}</li></ul><code>证据：{{x.evidence_content_ids.join(', ')}}</code></article></div><form v-if="room.status==='open'" class="stack" @submit.prevent="addOption"><input v-model="option.title" required placeholder="选项"><textarea v-model="option.constraints" placeholder="每行一个约束"></textarea><textarea v-model="option.benefits" placeholder="每行一个收益"></textarea><textarea v-model="option.effects" placeholder="每行一个副作用"></textarea><input v-model="option.evidence" required placeholder="证据内容 ID，以逗号分隔"><button>加入决策选项</button></form></div><h3>审计</h3><p v-for="x in room.audit"><time>{{new Date(x.created_at).toLocaleString()}}</time> {{x.action}}</p></template></section>
<section v-else><h2>翻译质量、推演准确性与长期回测</h2><div class="notice"><strong>当前证据质量状态</strong><p>翻译质量分数仅在经人工或受控评测数据集验证后写入。推演不输出“准确率”假指标；必须以事后实际结果和保留的来源范围完成回测。</p></div><div class="quality"><span>翻译：{{cap.translation_requires_approved_model?'批准模型必需':'不可用'}}</span><span>叙事：{{cap.narratives_require_cross_language_evidence?'跨语言证据必需':'不可用'}}</span><span>信号：人工复核必需</span><span>冻结：{{cap.decision_freeze_is_immutable?'不可变':'未启用'}}</span></div></section>
</template></main></template>
<style scoped>.global{min-height:100vh;padding:30px;background:#f4f6f5;color:#17231f}.global header,.head{display:flex;justify-content:space-between;align-items:end;gap:20px}.global h1{margin:5px 0;font-size:31px}.global h2{font-size:20px}.global p{color:#62716a}.global small{color:#176f67;font-weight:800}.tenant{color:#516058}nav{display:flex;overflow:auto;border-bottom:1px solid #cbd6d1;margin:24px 0}nav button{white-space:nowrap;border:0;background:none;padding:12px 14px}nav .active{border-bottom:2px solid #176f67;color:#176f67}.metrics,.quality{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #d5dfda}.metrics article,.quality span{padding:16px;background:#fff;border-right:1px solid #d5dfda}.metrics span,.metrics strong{display:block}.metrics strong{font-size:25px}.map,.decision{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:22px}.world{min-height:300px;display:flex;flex-wrap:wrap;align-content:center;gap:13px;padding:20px;background:#173b38;color:#e9f3ef}.world b{width:100%}.world span{padding:10px;background:#3a8277}.world p{color:#c5d5cf}.map ol{list-style:none;padding:0}.map li{display:grid;grid-template-columns:100px 1fr;gap:8px;padding:11px 0;border-bottom:1px solid #d5dfda}.map li span{grid-column:2;color:#6d7c75}form{display:flex;gap:9px;margin:14px 0;max-width:900px}.stack{display:grid;max-width:650px}input,select,textarea{min-width:0;padding:10px;border:1px solid #bac8c1;border-radius:4px;background:#fff}textarea{min-height:80px}button{border:0;border-radius:4px;padding:9px 13px;background:#176f67;color:#fff;cursor:pointer}.translation,.scenario{margin:12px 0;padding:16px;background:#fff;border-left:3px solid #176f67}.translation h3,.scenario h3{margin:8px 0}.rows article{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:16px 0;border-bottom:1px solid #d2dcd7}.rows strong,.rows span,.rows small{display:block}.rows aside b{display:inline-block;padding:4px 7px;background:#fff0cf;color:#705510;margin:2px}.rows aside i{color:#617069}.scenario b{display:block;margin:5px 0;color:#8a4148}.decision>div article{padding:14px;margin:10px 0;background:#fff;border-left:3px solid #3c7e74}.decision code{display:block;overflow:auto}.notice{max-width:800px;padding:16px;background:#fff5d9;border-left:3px solid #b77b16}.empty{padding:60px;text-align:center;color:#6d7973}@media(max-width:760px){.global{padding:76px 12px 24px}.global header{display:block}.tenant{margin-top:8px}.metrics,.quality{grid-template-columns:1fr 1fr}.map,.decision,.rows article{grid-template-columns:1fr}form{display:grid}.map li{grid-template-columns:1fr}.map li span{grid-column:auto}}</style>
