<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{operationsApi}from'@/api/operations'
const open=ref('start'),sending=ref(false);const feedback=reactive({category:'idea',rating:5,message:''})
const topics=[{id:'start',title:'开始使用',body:'先在数据源中心连接公开来源并完成同步，再到 Discover 或搜索中心查看真实内容。Workspace 只聚合已有数据，不生成模拟建议。'},{id:'evidence',title:'引用与可信度',body:'AI 分析、Agent 和报告中的事实结论必须附带来源。证据不足时系统会拒绝给出结论。'},{id:'alerts',title:'预警处置',body:'创建规则后先执行历史回放。真实触发可确认、分派、记录处置、关闭或标记误报，状态变化进入审计记录。'},{id:'privacy',title:'隐私与删除',body:'知识库按用户隔离。删除文档后无法继续召回；删除账号需要再次验证密码，并删除私有文件及关联数据。'},{id:'support',title:'问题诊断',body:'请求失败时记录诊断编号、时间和操作入口。不要提交访问令牌、Cookie、Webhook 密钥或私有文档正文。'}]
async function submitFeedback(){sending.value=true;try{await operationsApi.feedback(feedback);feedback.message='';ElMessage.success('反馈已提交')}finally{sending.value=false}}
onMounted(()=>operationsApi.track('help_opened','/help').catch(()=>undefined))
</script>
<template><main><header><small>PRODUCT GUIDE</small><h1>帮助中心</h1><p>按工作流程查找操作说明、证据规则和故障处理入口。</p></header><section class="guide"><nav aria-label="帮助主题"><button v-for="topic in topics" :key="topic.id" :class="{active:open===topic.id}" @click="open=topic.id">{{topic.title}}</button></nav><article v-for="topic in topics" v-show="open===topic.id" :key="topic.id"><span>{{String(topics.indexOf(topic)+1).padStart(2,'0')}}</span><h2>{{topic.title}}</h2><p>{{topic.body}}</p></article></section><section class="quick"><h2>常用入口</h2><div><router-link to="/sources">数据源中心</router-link><router-link to="/search">搜索中心</router-link><router-link to="/alerts">预警中心</router-link><router-link to="/knowledge">知识库</router-link></div></section><section class="feedback"><div><small>FEEDBACK</small><h2>提交产品反馈</h2><p>请勿填写访问令牌、Cookie、Webhook 密钥或私有文档正文。</p></div><form @submit.prevent="submitFeedback"><select v-model="feedback.category" aria-label="反馈类型"><option value="bug">问题</option><option value="idea">建议</option><option value="data_quality">数据质量</option><option value="ai_quality">AI 质量</option><option value="other">其他</option></select><select v-model="feedback.rating" aria-label="满意度"><option v-for="n in 5" :key="n" :value="n">{{n}} 分</option></select><textarea v-model="feedback.message" minlength="3" maxlength="2000" required placeholder="描述你遇到的问题或建议"/><button :disabled="sending">提交反馈</button></form></section></main></template>
<style scoped>main{padding:30px;min-height:100vh;background:#f5f7f8;color:#17211d}header{max-width:760px}header small,.feedback small{color:#176f67;font-weight:800}h1{margin:5px 0;font-size:30px}header p,.feedback p{color:#65706b}.guide{display:grid;grid-template-columns:250px minmax(0,1fr);margin-top:28px;border:1px solid #d8e0dd;background:#fff;min-height:360px}.guide nav{display:flex;flex-direction:column;padding:12px;border-right:1px solid #e0e6e3}.guide button{padding:13px;border:0;border-radius:4px;background:none;text-align:left;color:#4f5c57}.guide button.active{background:#e8f2ef;color:#176f67;font-weight:700}.guide article{padding:36px;max-width:740px}.guide article span{color:#a64a42;font-weight:800}.guide article p{line-height:1.8;color:#52605a}.quick{margin-top:24px}.quick div{display:flex;flex-wrap:wrap;gap:8px}.quick a{padding:10px 13px;border:1px solid #cfd9d5;border-radius:4px;background:#fff;color:#176f67;text-decoration:none}.feedback{display:grid;grid-template-columns:260px 1fr;gap:24px;margin-top:26px;padding:24px 0;border-top:1px solid #d8e0dd}.feedback form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.feedback select,.feedback textarea{border:1px solid #cbd6d2;border-radius:4px;padding:10px;background:#fff}.feedback textarea{grid-column:1/-1;min-height:100px;resize:vertical}.feedback button{justify-self:start;border:0;border-radius:4px;padding:10px 16px;background:#176f67;color:#fff}.feedback button:disabled{opacity:.5}@media(max-width:720px){main{padding:76px 12px 20px}.guide{display:block}.guide nav{border-right:0;border-bottom:1px solid #e0e6e3}.guide article{padding:24px 18px}.feedback{grid-template-columns:1fr}.feedback form{grid-template-columns:1fr}.feedback textarea{grid-column:auto}}</style>
