<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { reportsApi, type ReportType } from '@/api/reports'

const router = useRouter(), route = useRoute(), reports = ref<any[]>([]), templates = ref<any[]>([])
const loading = ref(true), creating = ref(false), dialog = ref(false), query = ref(''), typeFilter = ref('')
const draft = ref<{ title: string; report_type: ReportType }>({ title: '', report_type: 'daily' })
const filtered = computed(() => reports.value.filter(r => (!typeFilter.value || r.report_type === typeFilter.value) && (!query.value || r.title.toLowerCase().includes(query.value.toLowerCase()))))
const names: Record<string, string> = { daily: '日报', weekly: '周报', event: '事件报告', industry: '行业报告', executive: '领导简报', risk: '风险报告' }
async function load() { loading.value = true; try { [reports.value, templates.value] = await Promise.all([reportsApi.list(), reportsApi.templates()]) } finally { loading.value = false } }
function sourceConfig() { const q = route.query; return { event_ids: q.event_id ? [String(q.event_id)] : [], analysis_ids: q.analysis_id ? [String(q.analysis_id)] : [], message_ids: q.message_id ? [String(q.message_id)] : [], content_ids: q.content_ids ? String(q.content_ids).split(',').filter(Boolean) : [], include_favorites: q.favorites === '1' } }
function start(template: any) { draft.value = { title: `${template.name} ${new Date().toLocaleDateString()}`, report_type: template.id }; dialog.value = true }
async function create() { if (!draft.value.title.trim()) return; creating.value = true; try { const result = await reportsApi.create({ ...draft.value, source_config: sourceConfig() }); dialog.value = false; await router.push(`/reports/${result.id}`) } finally { creating.value = false } }
async function remove(item: any) { await ElMessageBox.confirm(`删除“${item.title}”？`, '删除报告'); await reportsApi.remove(item.id); ElMessage.success('报告已删除'); await load() }
async function copy(item: any) { const detail = await reportsApi.detail(item.id); const created = await reportsApi.create({ title: `${item.title}（副本）`, report_type: item.report_type, source_config: detail.source_config }); await reportsApi.saveVersion(created.id, { content_markdown: detail.current_version.content_markdown, structured_content: detail.current_version.structured_content, citation_content_ids: detail.current_version.citations.map((c: any) => c.content_id) }); await router.push(`/reports/${created.id}`) }
onMounted(load)
</script>
<template><main class="reports-page"><header><div><small>REPORT CENTER</small><h1>报告中心</h1><p>将真实情报整理为可编辑、可追溯、可交付的正式报告。</p></div><button @click="start(templates[0] || { id: 'daily', name: '日报' })"><el-icon><Plus /></el-icon>新建报告</button></header>
<section class="templates"><button v-for="t in templates" :key="t.id" @click="start(t)"><el-icon><Document /></el-icon><strong>{{t.name}}</strong><span>{{t.outline?.slice(0,3).join(' · ')}}</span></button></section>
<div class="filters"><el-input v-model="query" clearable placeholder="搜索报告" prefix-icon="Search"/><el-select v-model="typeFilter" clearable placeholder="全部类型"><el-option v-for="(name,key) in names" :key="key" :label="name" :value="key"/></el-select></div>
<section v-loading="loading" class="report-list"><article v-for="r in filtered" :key="r.id"><div class="type">{{names[r.report_type] || r.report_type}}</div><div><h2>{{r.title}}</h2><p>更新于 {{new Date(r.updated_at).toLocaleString()}} · {{r.status === 'draft' ? '草稿' : r.status}}</p></div><div class="actions"><button title="复制" @click="copy(r)"><el-icon><CopyDocument /></el-icon></button><button title="删除" @click="remove(r)"><el-icon><Delete /></el-icon></button><button class="continue" @click="router.push(`/reports/${r.id}`)">继续编辑<el-icon><ArrowRight /></el-icon></button></div></article><div v-if="!loading && !filtered.length" class="empty"><el-icon><Document /></el-icon><h2>还没有符合条件的报告</h2><p>从模板开始，或从事件、搜索、收藏、AI 分析和 Agent 结果创建。</p></div></section>
<div v-if="dialog" class="modal-backdrop" style="position:fixed;inset:0;z-index:600;display:grid;place-items:center;padding:18px;background:rgba(12,29,23,.42);backdrop-filter:blur(2px)" @click.self="dialog=false"><form class="create-modal" style="width:min(500px,100%);padding:22px;border-radius:7px;background:#fff;box-shadow:0 24px 70px rgba(10,25,20,.22)" @submit.prevent="create"><header style="display:flex;align-items:center;justify-content:space-between"><h2>创建报告</h2><button type="button" title="关闭" @click="dialog=false"><el-icon><Close /></el-icon></button></header><label style="margin-top:18px;display:grid;gap:7px">报告类型<select v-model="draft.report_type" style="height:40px"><option v-for="(name,key) in names" :key="key" :value="key">{{name}}</option></select></label><label style="margin-top:18px;display:grid;gap:7px">标题<input v-model="draft.title" style="height:40px" maxlength="300" required/></label><footer style="margin-top:24px;display:flex;justify-content:flex-end;gap:8px"><button type="button" @click="dialog=false">取消</button><button class="primary" :disabled="creating">{{creating?'正在创建':'创建并编辑'}}</button></footer></form></div></main></template>
<style scoped>.reports-page{min-height:100vh;padding:36px clamp(18px,4vw,64px);color:#17231f;background:#f3f6f5}.reports-page>header{display:flex;align-items:end;justify-content:space-between;padding-bottom:24px;border-bottom:1px solid #cbd7d2}.reports-page h1{margin:6px 0;font:650 40px Georgia,"Songti SC",serif}.reports-page header small{color:#167f76;font-weight:800}.reports-page header p{margin:0;color:#687b74}.reports-page header button,.continue{height:40px;padding:0 14px;border:0;border-radius:5px;display:flex;align-items:center;gap:6px;color:#fff;background:#183129}.templates{padding:22px 0;display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.templates button{min-height:92px;padding:14px;border:1px solid #cbd7d2;border-radius:6px;display:grid;gap:7px;text-align:left;color:#20352e;background:#fff;cursor:pointer}.templates button:hover{border-color:#167f76}.templates span{overflow:hidden;color:#758780;font-size:11px;text-overflow:ellipsis;white-space:nowrap}.filters{display:grid;grid-template-columns:minmax(220px,420px) 160px;gap:10px;margin-bottom:12px}.report-list{min-height:300px;border:1px solid #cbd7d2;border-radius:7px;background:#fff}.report-list article{min-height:88px;padding:14px 16px;display:grid;grid-template-columns:90px 1fr auto;gap:18px;align-items:center;border-top:1px solid #e0e7e4}.report-list article:first-child{border-top:0}.type{color:#167f76;font-size:12px;font-weight:800}.report-list h2{margin:0;font-size:17px}.report-list p{margin:7px 0 0;color:#778780;font-size:11px}.actions{display:flex;gap:6px}.actions>button{height:34px;border:1px solid #d1dcd7;border-radius:4px;background:#fff}.actions .continue{height:34px;border:0}.empty{min-height:330px;display:grid;place-items:center;align-content:center;color:#788982;text-align:center}.empty>.el-icon{font-size:44px}.empty h2{margin:14px 0 0}.empty p{max-width:520px}@media(max-width:900px){.templates{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.reports-page>header{align-items:flex-start;gap:12px}.reports-page h1{font-size:32px}.reports-page header p{display:none}.templates{grid-template-columns:repeat(2,1fr)}.filters{grid-template-columns:1fr}.report-list article{grid-template-columns:1fr}.type{order:0}.actions{justify-content:flex-end}}</style>
