<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{trustNetworkApi}from'@/api/trustNetwork'
const overview=ref<any>({}),inbox=ref<any[]>([]),tab=ref('network')
const agreement=reactive({partner_organization_id:'',purpose:'anonymous-benchmark',allowed_metrics:['sla_minutes'],regions:['global'],minimum_cohort:10}),product=reactive({key:'risk-signals',name:'跨区域风险信号',description:'经过策略裁剪的聚合风险指标',license_terms:{purpose:'risk-monitoring'},quality_sla:{freshness_minutes:60},price_cents:9900,currency:'CNY',revenue_share_percent:80}),regulatory=reactive({key:'ai-governance',version:1,industry:'technology',region:'global',rules:{human_approval:true},rollback_of_version:null}),drill=reactive({scenario:'vendor_exit',participants:['operations','security'],expected_controls:['provider-fallback','credential-revoke'],evidence:{runbook:'verified'},containment_minutes:15,recovery_minutes:45})
async function load(){[overview.value,inbox.value]=await Promise.all([trustNetworkApi.overview(),trustNetworkApi.inbox()])}
async function saveAgreement(){await trustNetworkApi.agreement(agreement);ElMessage.success('联邦协议已创建');agreement.partner_organization_id='';await load()}
async function saveProduct(){await trustNetworkApi.product(product);ElMessage.success('情报产品已上架');await load()}
async function saveRegulatory(){await trustNetworkApi.regulatory(regulatory);ElMessage.success('监管规则包已签名发布');await load()}
async function saveDrill(){const x=await trustNetworkApi.drill(drill);ElMessage[x.status==='passed'?'success':'error'](`生态演练：${x.status}`);await load()}
onMounted(load)
</script>
<template><main><header><div><small>TRUSTED INTELLIGENCE NETWORK</small><h1>可信情报网络</h1><p>跨组织交换聚合信号、验证数据血缘并治理情报产品交易。</p></div><span class="trust">签名与隐私门禁</span></header><div class="metrics"><article v-for="(v,k) in overview" :key="k"><span>{{String(k).replaceAll('_',' ')}}</span><strong>{{v}}</strong></article></div><nav><button :class="{active:tab==='network'}" @click="tab='network'">联邦网络</button><button :class="{active:tab==='market'}" @click="tab='market'">情报市场</button><button :class="{active:tab==='governance'}" @click="tab='governance'">监管与韧性</button></nav>
<section v-if="tab==='network'" class="grid"><form @submit.prevent="saveAgreement"><h2>建立联邦协议</h2><label>合作租户 ID<input v-model="agreement.partner_organization_id" required/></label><label>用途<input v-model="agreement.purpose" required/></label><label>最小匿名群组<input v-model.number="agreement.minimum_cohort" type="number" min="5"/></label><div class="scope"><span>允许指标</span><code>{{agreement.allowed_metrics.join(', ')}}</code></div><button>创建协议</button></form><div class="panel"><h2>接收信封</h2><div v-for="x in inbox" :key="x.id" class="row"><span><strong>{{x.metric_key}}</strong><small>{{x.privacy?.cohort_size}} 个样本</small></span><code>{{x.signature.slice(0,12)}}</code></div><p v-if="!inbox.length" class="empty">暂无可用交换信封</p></div></section>
<section v-else-if="tab==='market'" class="grid"><form @submit.prevent="saveProduct"><h2>发布情报产品</h2><label>产品标识<input v-model="product.key" required/></label><label>名称<input v-model="product.name" required/></label><label>描述<textarea v-model="product.description"/></label><div class="pair"><label>价格（分）<input v-model.number="product.price_cents" type="number" min="0"/></label><label>供应方分成 %<input v-model.number="product.revenue_share_percent" type="number" min="0" max="100"/></label></div><button>上架产品</button></form><div class="panel"><h2>交易保障</h2><ul><li>授权后才能交付</li><li>交付回执包含内容校验和</li><li>供应方与平台分账严格守恒</li><li>退款与争议保留支付引用</li></ul></div></section>
<section v-else class="grid"><form @submit.prevent="saveRegulatory"><h2>全球监管规则包</h2><label>规则包标识<input v-model="regulatory.key"/></label><div class="pair"><label>行业<input v-model="regulatory.industry"/></label><label>地域<input v-model="regulatory.region"/></label></div><label>版本<input v-model.number="regulatory.version" type="number" min="1"/></label><button>签名发布</button></form><form @submit.prevent="saveDrill"><h2>生态韧性演练</h2><label>场景<select v-model="drill.scenario"><option value="vendor_exit">供应商退出</option><option value="regional_outage">区域断网</option><option value="key_compromise">密钥泄漏</option><option value="data_poisoning">数据投毒</option><option value="settlement_outage">结算中断</option></select></label><div class="pair"><label>遏制分钟<input v-model.number="drill.containment_minutes" type="number"/></label><label>恢复分钟<input v-model.number="drill.recovery_minutes" type="number"/></label></div><button>记录演练</button></form></section></main></template>
<style scoped>main{min-height:100vh;padding:30px;background:#f4f7f6;color:#17231f}header{display:flex;justify-content:space-between}header small{color:#14756b;font-weight:800}h1{margin:4px 0}header p{margin:0;color:#68756f}.trust{height:fit-content;padding:7px 10px;border:1px solid #afd3c6;background:#e6f4ef;color:#13675e;border-radius:4px}.metrics{display:grid;grid-template-columns:repeat(7,1fr);margin-top:24px;background:#fff;border:1px solid #d7e1dd}.metrics article{padding:14px;border-right:1px solid #e1e7e5}.metrics span,.metrics strong{display:block}.metrics span{text-transform:capitalize;color:#718079;font-size:10px}.metrics strong{margin-top:5px;font-size:22px}nav{display:flex;margin:22px 0;border-bottom:1px solid #cdd8d4}nav button{padding:11px 15px;border:0;background:none;cursor:pointer}nav .active{color:#126f66;border-bottom:2px solid #126f66}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}form,.panel{padding:18px;background:white;border:1px solid #d7e0dd}form{display:grid;gap:11px}label{display:grid;gap:5px;color:#63716b;font-size:12px}input,textarea,select{box-sizing:border-box;width:100%;padding:10px;border:1px solid #c8d5d0;border-radius:4px}textarea{min-height:70px}form button{justify-self:start;padding:10px 14px;border:0;border-radius:4px;background:#176f67;color:white}.pair{display:grid;grid-template-columns:1fr 1fr;gap:10px}.scope{padding:12px;background:#eef4f2}.scope span,.scope code{display:block}.row{display:flex;justify-content:space-between;padding:11px;border-bottom:1px solid #e2e8e5}.row span{display:grid}.row small{color:#74817b}.empty{text-align:center;padding:30px;color:#77837d}li{margin:12px 0}@media(max-width:920px){.metrics{grid-template-columns:repeat(4,1fr)}}@media(max-width:720px){main{padding:76px 12px 20px}.grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}}</style>
